### ISSUE TITLE
Feature Request: MT32 

### ISSUE THREAD

**Issue by robbo007** [litchie/dospad#1]
Hi Litchie,
Can you please add support for Roland MT32 using real Roland MT32 roms. There are currently two builds of DOSBOX with this support. Form Windows and MAC.

http://www.sierrahelp.com/Utilities/Emulators/Munt.html
or 
http://boxerapp.com

Also would be good to be able to mount ISO's to be used with dosgames that require the CDROM with speech etc.
Thanks
Rob

**Comment by DominusExult** [comment]
To implement this you need to get Munt working, which should not be that hard with the "official" munt patch at https://github.com/munt/munt/tree/master/DOSBox-mt32-patch
The ages old Munt implementation (and not all that accurate as the current MUNT code) in Exult is already working with your exult-ios when you put the ROMs in the data folder in itunes file sharing :)

**Comment by litchie** [comment]
Thanks for the link!

**Comment by DominusExult** [comment]
No problem, just be aware of two things I forgot to mention:
- MT32 emulation is CPU demanding and coupled with a demanding game this could mean too much strain and the game or the music becomes choppy. The MT32 emulation will also most probable drain the battery very fast.

- the ROMs are a bit in a legal grey area, protect yourself, don't offer them for download ;)

**Comment by robbo007** [comment]
I'm happy to test it Litchie :)

Rob Craig
Twitter:@robcraig
Website:www.robcraig.com

**Comment by robbo007** [comment]
Let's see if the iPhone 6 can handle it ...

Rob Craig
Twitter:@robcraig
Website:www.robcraig.com
