### ISSUE TITLE
Compressed audio tracks

### ISSUE THREAD

**Issue by thehype1234** [litchie/dospad#10]
Hi...

I have 4 things in my mind, that would be awesome if you could add them to idos2
1. Mfi controller support
2. Fully customizable virtual controls for every single game... Maybe with an win/Mac app!?
   I think of playing flying or space sim games ;) 
3. Support for compressed audio files in cue sheets... Mixed mode CDs are really big 😁
4. An option to disable the mouse click on the whole display and maybe to make the mouse buttons bigger

Thx for an answer and sorry for the bad english

**Comment by litchie** [comment]
Thank you for reposting your requests.

**Comment by thehype1234** [comment]
You're welcome... 
Is there any compressed audio file support at the moment?
I have tested MP3 and ogg files, but mscdex keeps saying  invalid file or unable to open!

**Comment by DominusExult** [comment]
Dosbox and I guess dospad needs SDL_sound to make cue files with ogg audio tracks to work. Right now it looks as if SDL_sound is not included in dospad.

**Comment by thehype1234** [comment]
But isn't this only a switch to activate it? I have read the dosbox wiki and this says it must set to 1...

**Comment by DominusExult** [comment]
No, these instructions are for another system/compiler. You still need to HAVE SDL_sound source AND (perhaps a bigger hurdle) it needs to compile for iOS/ARM (and it needs to be added to the Xcode project file).

**Comment by litchie** [comment]
1 and 2 fixed. 4 will be done in next update. Let's dedicate this to 3.

**Comment by litchie** [comment]
@thehype1234 Is it possible to share some test files?
