### ISSUE TITLE
UI - Floppy Drive on iPad does not open Recents like on iPhone

### ISSUE THREAD

**Issue by xanthiacoder** [litchie/dospad#100]
Love the new UI updates on the iPhone! Especially being able to see recent .iDOS packages. 

Not sure if I made a mistake with updating on my iPad, but it seems the Disk Drive at the top of the iPad UI doesn't seem to do the same thing (no response on iPad).

**Comment by litchie** [comment]
At the moment, this update is only for iPhone. Work on iPad is still going on. The reason to push iPhone update first is to see if people like it or not.

**Comment by litchie** [comment]
By the way,  you must launch iDOS package from Files app, otherwise it will be mounted as disk D only.

**Comment by xanthiacoder** [comment]
yes i noticed that. I tried to mount multiples. noticed that it is simply an automated shortcut for the mount. perhaps there can be a way to internally track which is the last drive letter used, then let the Recents trigger a mount command with an incremental increase in drive letter?

**Comment by litchie** [comment]
I will try to do that in future updates.
