### ISSUE TITLE
Smart Keyboard Key Repetition

### ISSUE THREAD

**Issue by maciekish** [litchie/dospad#102]
Hi, I have an iPad Pro 12.9" on iOS 14.2 with a Smart Keyboard. I have built the latest version from source today, and when i try to play Duke Nukem 3D, the movement with arrow keys is very jerky. It seems like dospad sends multiple keystrokes per second repeatedly instead of holding the key down. Iirc i could play it properly a couple months ago, has something with the keyboard support changed? Is it possible to use the previous implementation?

**Comment by litchie** [comment]
You should try to build with Release configuration, not appstore.

**Comment by Negenii** [comment]
Release configuration doesn't seem to help

**Comment by litchie** [comment]
It should be fixed by 2.6.
