### ISSUE TITLE
MT32 Emulation

### ISSUE THREAD

**Issue by ecstaticax** [litchie/dospad#105]
I downloaded from AppStore the latest update which contains MT32 emulation (great!!!), but honestly I don’t know how to test it. How does it work?

Addendum: can someone explain me how to configure midi under Windows 3.1 using MT32 emulation?

**Comment by firecrafts** [comment]
you need 3 things :- 
- A game that have Roland MT-32 support : here a link that sort all Dos games that support it https://en.wikipedia.org/wiki/List_of_MT-32-compatible_computer_games
- you need to have 2 MT32 roms [ MT32_CONTROL.ROM + MT32_PCM.ROM ] you put them inside config folder of your .iDos package that have ur game
-last thing is edit your dospad.cfg inside config folder and type at start 
`[midi]

mpu401=intelligent
mididevice=mt32
midiconfig=
mt32.romdir=config
mt32.reverse.stereo=false
mt32.verbose=false
mt32.thread=true
mt32.chunk=16
mt32.prebuffer=32
mt32.partials=32
mt32.dac=0
mt32.analog=2
mt32.reverb.mode=auto
mt32.reverb.time=5
mt32.reverb.level=3
        ` 
and now you are ready to setup your game to use roland mt-32 sound card :D 

here example of the diffrent between mt32 and adlib : https://www.youtube.com/watch?v=0-uAf_xMQSQ

hope i helped you ^_^

**Comment by xanthiacoder** [comment]
Great guide and tips! Would it be correct to say that now with this support, it would make sense to have those lines in the default cfg? at the most, maybe commented out so default state remains but is easy for a user to uncomment to activate, like GUS support.

**Comment by firecrafts** [comment]
its can mess up i think if you make it default for games that not supporting mt32
but maybe setting UI like pick sound card for idos and automatic saving it inside .iDos package will be userfriendly idea

**Comment by xanthiacoder** [comment]
I am thinking it will probably be an easy add-on to include a batch file that can help users with switching configurations. worth being a feature request?

**Comment by xanthiacoder** [comment]
I am actually working on some simplified process to switch between Gravis Ultrasound (GUS) and SB16. perhaps now with MT-32, worth looking into a user-friendly sound support switcher.

**Comment by firecrafts** [comment]
for feature request yeah but i think there is other more important stuff need to work on right now 
like they are working i think on direct touch support ( good for point and click / rts games ) and make mouse more useable 
and i wish add 3dfx voodoo support one day :P

**Comment by xanthiacoder** [comment]
no worries. I can take on this functionality. I will work on it and submit for deployment inclusion if it is working well.

**Comment by firecrafts** [comment]
eXo had done it this way 
```
:menu
@echo off
cls
echo.
echo Press 1 for X-COM: UFO Defense w/ SoundBlaster
echo Press 2 for X-COM: UFO Defense w/ MT32
echo Press 3 for X-COM: UFO Defense w/ Sound Canvas
echo Press 4 to Quit
echo.
choice /C:1234 /N Please Choose:

if errorlevel = 4 goto quit
if errorlevel = 3 goto SC55
if errorlevel = 2 goto MT32
if errorlevel = 1 goto SB

:SB
CONFIG -set "mididevice=default"
@cd sound
cls
copy .\sb\*.* .\
cd..
cls
@call RUNXCOM
goto quit

:MT32
CONFIG -set "mididevice=mt32"
@cd sound
cls
copy .\mt32\*.* .\
cd..
cls
@call RUNXCOM
goto quit

:SC55
CONFIG -set "mididevice=fluidsynth"
@cd sound
cls
copy .\sc55\*.* .\
cd..
cls
@call RUNXCOM
goto quit

:quit
exit
```

**Comment by firecrafts** [comment]
i wonder if sound Canvas is supported in iDos2

**Comment by litchie** [comment]
> Great guide and tips! Would it be correct to say that now with this support, it would make sense to have those lines in the default cfg? at the most, maybe commented out so default state remains but is easy for a user to uncomment to activate, like GUS support.

Good idea!

**Comment by litchie** [comment]
> i wonder if sound Canvas is supported in iDos2

What is this? Please educate me:)

**Comment by xanthiacoder** [comment]
https://en.m.wikipedia.org/wiki/Roland_SC-55

Sound Canvas SC-55

was around during DOS era. I actually had the hardware. Quite good for music.

**Comment by xanthiacoder** [comment]
https://gamefaqs.gamespot.com/boards/204-classic-gaming/73333812

more SC-55 info

**Comment by ecstaticax** [comment]
> you need 3 things :-
> 
> * A game that have Roland MT-32 support : here a link that sort all Dos games that support it https://en.wikipedia.org/wiki/List_of_MT-32-compatible_computer_games
> * you need to have 2 MT32 roms [ MT32_CONTROL.ROM + MT32_PCM.ROM ] you put them inside config folder of your .iDos package that have ur game
> * last thing is edit your dospad.cfg inside config folder and type at start
> 
> ```
> [midi]
> 
> mpu401=intelligent
> mididevice=mt32
> midiconfig=
> mt32.romdir=config
> mt32.reverse.stereo=false
> mt32.verbose=false
> mt32.thread=true
> mt32.chunk=16
> mt32.prebuffer=32
> mt32.partials=32
> mt32.dac=0
> mt32.analog=2
> mt32.reverb.mode=auto
> mt32.reverb.time=5
> mt32.reverb.level=3
>        
> ```
> 
> and now you are ready to setup your game to use roland mt-32 sound card :D
> 
> here example of the diffrent between mt32 and adlib : https://www.youtube.com/watch?v=0-uAf_xMQSQ
> 
> hope i helped you ^_^

Thanks a lot for replying. I use iDos using a simulated hd, where I have a lot of directories with games, apps, and even windows 3.1 installed. Honestly I don’t know what a idos package is. I presume I need to copy the mt32 roms inside the /config directory? How can I have different .idos packages? 
On windows 3.1can I also emulate a midi external interface using MT32 emulation?

**Comment by ecstaticax** [comment]
I configure it for games, and works like a charm! Great.
I would like to output Cakewalk midi on Windows 3.1....

**Comment by DominusExult** [comment]
> i wonder if sound Canvas is supported in iDos2

There used to be Roland's Virtual Sound Canvas which connects to coremidi and in theory iDOS could connect to, but the app is gone from the AppStore :(

**Comment by xanthiacoder** [comment]
> > i wonder if sound Canvas is supported in iDos2
> 
> 
> 
> There used to be Roland's Virtual Sound Canvas which connects to coremidi and in theory iDOS could connect to, but the app is gone from the AppStore :(

https://apps.apple.com/sg/app/midi-sweet-module-unit-au/id1496123942

There are options. not free though. still searching around.

**Comment by ecstaticax** [comment]
> > i wonder if sound Canvas is supported in iDos2
> 
> There used to be Roland's Virtual Sound Canvas which connects to coremidi and in theory iDOS could connect to, but the app is gone from the AppStore :(

I have a lot of midi apps. I also have Roland sound canvas installed. How can I configure idos to support core midi?

**Comment by DominusExult** [comment]
You might need to wait for Litchie to use current SVN of Dosbox as that has more options for Coremidi

**Comment by ecstaticax** [comment]
> You might need to wait for Litchie to use current SVN of Dosbox as that has more options for Coremidi

Litchie do you think you will update to latest svn?

**Comment by litchie** [comment]
Will look into it.

**Comment by cyberluke** [comment]
any news?

**Comment by litchie** [comment]
dospad has merged in the latest dosbox svn. Sound fonts are also supported (midi=coreaudio).
