### ISSUE TITLE
Gamepad Mapper not working

### ISSUE THREAD

**Issue by yoshisuga** [litchie/dospad#106]
Hi! Thanks for adding MT-32 support - it sounds amazing and it's an awesome addition!

The gamepad mapper looks like it was rewritten but it doesn't look complete. It doesn't appear when the Bluetooth icon is tapped.

I looked into it and ran it through the view debugger and found that the `MfiGamepadMapperView` is being displayed behind the `UIImageView` main emulator screen. This is because `DPEmulatorViewController.viewDidLayoutSubviews` is placing the main emulator screen in the front always.

To get it to appear, I made  `MfiGamepadMapperView`a property of the `DOSPadBaseViewController`, and in `viewDidLayoutSubviews`:
```
    if (self.mfiMapper) {
        [self.view bringSubviewToFront:self.mfiMapper];
    }
```

![IMG_2BC1A97A900B-1](https://user-images.githubusercontent.com/564774/100034597-a0292380-2da0-11eb-9fd7-eefd67205fe2.jpeg)

The problem is that there doesn't appear to be a way to map the buttons on pressing the button on the mfi controller - how is this supposed to work? Is the keyboard supposed to appear and one is able to map a button that way?

**Comment by litchie** [comment]
Thank you for your original work!

This is fixed in recent commits. (Just pushed)

1. After the mapper appears, you press button on your gamecontroller, then the corresponding button on the mapper will be highlighted.
2. Keep the button pressed, then you type on one of the keys in floating keyboard. Done

**Comment by yoshisuga** [comment]
Pulled and ran and it works great, thanks!! Very nice!
