### ISSUE TITLE
Hardware keyboard stops working after multitasking

### ISSUE THREAD

**Issue by logicalelegance** [litchie/dospad#107]
When using an iPad with a hardware keyboard, such as the official apple keyboard case, 
if you swipe another app over (say notes) and then dismiss it the keyboard stops functioning
within dospad. The virtual keyboard still works.

**Comment by litchie** [comment]
Thanks. I may know what's going on. Will fix it.

**Comment by logicalelegance** [comment]
Awesome thanks! I had a quick look and couldn’t see any missing delegates for focus change or anything. I’ll be interested to see what it was.

**Comment by bill-raynor** [comment]
The issue appears in the current app store version 2.6.1.   Is that specific to the app store?
