### ISSUE TITLE
Are u the developer of aemula?

### ISSUE THREAD

**Issue by SavagePy10** [litchie/dospad#109]

**Comment by litchie** [comment]
Yes?

**Comment by SavagePy10** [comment]
> Yes?

Im trying to boot linux on aemula. LOL

**Comment by litchie** [comment]
It doesn't work. Wait for future updates:-)

**Comment by SavagePy10** [comment]
> Yes?

If i modify init.I, can i use other bios?

**Comment by SavagePy10** [comment]
> It doesn't work. Wait for future updates:-)

Its been 7 years lol

**Comment by litchie** [comment]
Yes you can change bios, but it's more likely related to some bugs in the cpu emulation. I am going to rewrite it with ARM64 assembler, anyway.

**Comment by SavagePy10** [comment]
> Yes you can change bios, but it's more likely related to some bugs in the cpu emulation. I am going to rewrite it with ARM64 assembler, anyway.

20 MIPS is max. Can it be higher

**Comment by litchie** [comment]
Yes, at least double that.

**Comment by SavagePy10** [comment]
And will it be free XD

**Comment by litchie** [comment]
let's worry about that when it's actually done:)

CLOSING since it's not related to dospad.

**Comment by SavagePy10** [comment]
> let's worry about that when it's actually done:)
> 
> CLOSING since it's not related to dospad.

Oh i forgot to ask. Will android version get the update?

**Comment by litchie** [comment]
Yes, and perhaps RPi

**Comment by SavagePy10** [comment]
I will test it when its done. I will try linux again.

**Comment by BryleHelll** [comment]
🤔🤔 
Still no update about that app.

**Comment by litchie** [comment]
working on it, still a long way to go, but it's very promising.

**Comment by BryleHelll** [comment]
> working on it, still a long way to go, but it's very promising.

That's ok. What wierd is no one ever created a modded version…...

**Comment by BryleHelll** [comment]
Just kidding. App is paid so modded is illwgal

**Comment by BryleHelll** [comment]
Should add buil-in .img/.iso editior

**Comment by litchie** [comment]
Yes, I know, but that's not going to be in the first version.

**Comment by BryleHelll** [comment]
> Yes, I know, but that's not going to be in the first version.

Some website even classify aemula as abandonware.

**Comment by litchie** [comment]
I didn't expect there is still interest in aemula. I just want to make it work again.

**Comment by BryleHelll** [comment]
> I didn't expect there is still interest in aemula. I just want to make it work again.

Yeah there's still interest

**Comment by BryleHelll** [comment]
Just not that much
