### ISSUE TITLE
IDOS 2: File Sharing

### ISSUE THREAD

**Issue by jason0611** [litchie/dospad#11]
Ist it possible to enable file sharing via iTunes? Since IOS 8.3 it is impossible to use iDOS2 as used to. Maybe file sharing could lead to a directory accessible via the mount command...? :-)

**Comment by litchie** [comment]
I'd like to invite you to a beta version (with File Sharing enabled). Need your email.

**Comment by jason0611** [comment]
Hi,

here we are: martin@eller-essen.de

Greetings,
Martin

**Comment by jason0611** [comment]
Now I've set my email as public visible. :-)

**Comment by jason0611** [comment]
Have you got my email address, or are you still waiting?

**Comment by thehype1234** [comment]
I would be pleased to beta test a new version too! 😊

**Comment by ashers86** [comment]
Hi. Please could you send me the Beta as I too miss being able to place custom apps into idos?

Thanks and keep up the good work! :)

**Comment by arielscarpinelli** [comment]
can I get invited to that top?

**Comment by zero2029** [comment]
Hello everyone.... ITunes File Sharing has officially been enabled! I just updated my iDos 2 app from the iOS AppStore. Thank you litchie! You're the man!!! Now it would be nice to see iDos 2 have some badass features like dosbox turbo for android.... If possible. Wishful thinking...

**Comment by jason0611** [comment]
Seems to work fine. :-) Will make further testing next weekend. Thanks!

**Comment by jason0611** [comment]
Works very well. :-) I think my feature request can be closed now. Thanks again!

**Comment by jason0611** [comment]
iTunes Filesharing is now disabled again. Was that a "must do" by Apple, or what is the reason for this?

**Comment by litchie** [comment]
"Thanks" to Apple.

**Comment by thehype1234** [comment]
Could you enable it in secret mode? Lets say we can enter "filsharing" in dosbox and it pops up in itunes? Or is this not possible trough the api?

**Comment by litchie** [comment]
That can't be done in run time.

**Comment by patrickbusch** [comment]
In the emulator project Provenance someone included a web server that starts during runtime, which exposes the directory and that has bulk upload.
The pull request is here: https://github.com/jasarien/Provenance/issues/79

Maybe this would be something worth looking into?

**Comment by litchie** [comment]
That approach was tried, and rejected by Apple. Apparently the reviewer paid very close attention.

**Comment by patrickbusch** [comment]
Yes, I was afraid of that. The other project is open source and not distributed via app store.
But if I recall correctly anything that lets the user execute arbitrary code (like emulators) is forbidden and something like this would only allowed if all the programs come pre-packaged, without the possibility to change that.

**Comment by thehype1234** [comment]
How about an open in command from another app like izip or something else? You only have to get an unzip into the app and from there we can unzip the files needed!? Sorry if this is rubish... Just an idea! 😊

**Comment by litchie** [comment]
That was also tried.

**Comment by Yudster** [comment]
Could I possibly be in this beta?

**Comment by litchie** [comment]
Yes, see http://www.litchie.com/posts/20151027-idos-update-ios9.html

**Comment by Yudster** [comment]
Okay, I sent you a request email for the beta.

**Comment by Yudster** [comment]
Will you send me an email with a download for the beta?

**Comment by kylehuot12** [comment]
hey litchie can I be in the beta I forwarded the receipt for the idos purchase to idos@litchie.com.

**Comment by ndo360** [comment]
Hey I would love beta access with the file sharing. Been itching to play some dos games again.

Email: noahccline@gmail.com

**Comment by frobuddyharry** [comment]
Me Please Email:frobuddy2@gmail.com

**Comment by abkoomen** [comment]
Just bought this app to play some old dos games, shame file transfer doesnt work.
I would love to give the beta a try. abkoomen@multiweb.nl

**Comment by chisme** [comment]
Hello,

Can anyone tell me how to install the game without jailbreak? Also I would like to have access to beta test China.smiles@yahoo.com

**Comment by EriolGaurhoth** [comment]
I, too, would like a copy of the beta, if it's not too much trouble: fendercub5@gmail.com

**Comment by liquidearth** [comment]
Hi! i would like to get a beta copy too , thanks ! Here is my address : sz.majki8702@gmail.com

**Comment by thehype1234** [comment]
There is an app for msdos called mtcp which is enabling network protocols like a ftp server.
It is available under brutman.com
Is there any possibility to get idos ready, that it can run mtcp?
I have tested it and it says: 
Could not set packet driver
&
Failed to initialize tcp/ip 

Is this a problem with my configuration in idos or is it not possible to get network protocols running in idos?

**Comment by Euroaquilo** [comment]
Could you send it to me also plz? Would be much appreciated: euroaquilo@gmail.com

**Comment by alansmid** [comment]
Hi there! i wonder if i can get a beta versions :) Would be very appreciated, i just bought idos and idos 2

**Comment by jabz10** [comment]
I can I please get access to the beta too, much appreciated dansmitherson@gmail.com

**Comment by jason0611** [comment]
Hi,

is it possible to reenable me for beta testing again?

Kind regards,
Martin

**Comment by Jazzugg** [comment]
Hi, 

I wonder if i can get a beta versions,
Would be very appreciated, 
I just bought idos 2 and I would like to play Fallout 1 :)

Best regards

**Comment by frankiekam** [comment]
Hi litchie. 
My email address is **boonsengkam@gmail.com**
I purchased iDOS 2 yesterday for USD0.99. Please add my email to the beta list.  I am trying to add Digital Integration's Tornado (1993 DOS flight simulator) to the list of games playable by iDOS 2 on my iPad. But of course, iTunes file sharing has been disabled for iDOS 2 Version 1.4 and so no magic for now. Hope deferred makes the heart grow fonder.
Regards
Frankie Kam

**Comment by frankiekam** [comment]
How do I use the batch command 'count ' in iDOS 2 to cater for more than 9 inputs in the batch file menu? I've tried to use common DOS commands (code) that allow the user to input 2 characters, when tested using Windows' cmd window - works fine,  but in all cases so far the batch file when uploaded to iDOS 2's Documents, hangs. I want to be able to run more than the default max 9 DOS programs in iDOS 2.

**Comment by frankiekam** [comment]
BTW, jason0611, MANY THANKS for the beta redeem code which allowed me to install iDOS 2 (at last!!) on my iPad. I made a post on my blog about my achievement. https://goo.gl/AyFFvy

**Comment by jerrybasta** [comment]
Hello 
I Just bought app idos2 to play some old dos games, shame file transfer doesnt work.
I would love to give the beta a try please. 
My e-mail od: Jerry.basta@volny.cz

**Comment by CyberManifest** [comment]
Hello I bought iDOS 2 a while back but just installed the latest version from the app store recently and file transfer is disabled, understandably so, but I would like to add my own games; may I be added to the beta please? e-mail is ryan.k.mckee@gmail.com

**Comment by csomigliana** [comment]
Hello Litchie, I bought iDOS 2 on 4/8/2016 with the Apple ID somic@semelinanno.com 	
invoice nr. 1-720947694, order nr. MQHGSVWXN3, document nr, 127133312894.
I really would like to be in your beta test team, if still possible. You can use my Apple ID as email address (inbox only).
Thank you in advance for any consideration.
Best regards,

**Comment by GreenStarCross** [comment]
I bought Idos 2 and would like to get into the beta to play Xcom UFO defence.
My email is hayticehay@gmail.com
How ever my Apple ID email is hayticehay@hotmail.com

**Comment by orcf** [comment]
I bought iDOS 2 and I love to try the beta version
olivierfernandes@netmadeira.com
Thank you

**Comment by DosDokTor** [comment]
No fame, no shame, you can use iFunBox for accessing iDOS 2 files as I do. I do not have a jail broken iPad, but the app is reflushed by me using impact or as I will not ever pay for the fucking ten mb of data. Litchie,yes, deserves all the money, but, why such app like iDOS went to be paid, even when they pushed iTunes sharing out of it, btw the only way that you can put your games on it, is to open iFunBox, and open it's sandbox, they do not have what to do in this case.

**Comment by TKroggy** [comment]
I have found a way to add games without jailbreak and the IOS version does not matter as well, but I was running 9.3.5. You need IExplorer or Ifunbox or any app like that for the computer. Plug in the IOS device and open IExplorer. go to Media, then DCIM. Make a new folder and add the DOS files. save and unplug. Then open IDOS 2. go to EDIT then the DOS Shell. repeat the CD .. command untill you get to the c drive, OR C:/>. enter the command: Mount W: /private/var/mobile/Media/DCIM/
Then do CD FOLDERNAME and you will have your files! I have PAC-MAN running now!
Your Welcome :smiley:

**Comment by csomigliana** [comment]
To: TKroggy (sorry, but i could not find his comment in the blog)

Thank you for sharing.
I've tried it and I can mount properly the folder on disk W: but I can't see the files (added by me) nor run any program.

Any advise/solution?
Thank you for any reply and best regards,
Carlo

________________________________
Sent from a personal Apple Device
===========================

**Comment by RBadboys** [comment]
I have IDos 2 and would like to sign up for the beta so I can have the file sharing capability. My email is M_A_Workman@Yahoo.com.

Thank you

**Comment by TKroggy** [comment]
Csgm-
I program for DOS, so I have a lot of shells and .coms installed. One must have got the in from the root of my folders and worked. I will see if I can find the source or any other way.

**Comment by TKroggy** [comment]
Hey,
I was also wondering if I can get a beta verson of Idos 2. I want to see if I can write a simple program in it with QBasic as I could on the wifi homebrew port. My email is tkroggy1@gmail.com
Thanks😀

**Comment by Mmariusi** [comment]
Hi,
I have IDos 2 and would like to sign up for the beta if possible, so I can have the file sharing capability. My email is mmariusi@yahoo.com.
Thank you!

**Comment by BennoRetro** [comment]
Hi!
I have iDos2. Can I sign for the Beta?
Need iTunes file sharing support.
Big THX and go on with the good work

**Comment by bompelbob** [comment]
Please upload a version with working landscape mode to the app store.

**Comment by kamentsev** [comment]
Hi,
I`ve just bought IDos 2 and would like to sign up for the beta to have file sharing capability. Please email me kamentsev@gmail.com
Thank you!

**Comment by orcf** [comment]
Hello
Sorry to tell. I also buy idos2 and send email with the transaction and never got answers

**Comment by kamentsev** [comment]
Sad...

**Comment by DosDokTor** [comment]
Download Cydia Impactor, sideload iDOS2.ipa to iPad or iPhone, start it
once after that connect iOS to pc open iFunBox and open its sandbox, and
put there the files you need.

Pe 17 mai 2017 14:10, "kamentsev" <notifications@github.com> a scris:

**Comment by kamentsev** [comment]
iFunbox saying CONNECTION ERROR
![screen shot 2017-05-17 at 14 25 08](https://cloud.githubusercontent.com/assets/28754998/26151717/a9738fa0-3b0c-11e7-8ef9-14b5d943b450.png)

**Comment by kamentsev** [comment]
To install Cydia impactor Apple Developer certificate is needed.
It`s a kinda strange to buy an app in the AppStore for .99USD and than to buy one year 99$ certificate to use it

**Comment by DosDokTor** [comment]
No, man, make a icloud account and use it. It's TOTTALY free, why i would
use Cydia Impactor if it was a hundred fucking bucks instead of buying the
wanted app? Because it's fucking free, and i will never pay for a piece of
data.

Pe 17 mai 2017 14:51, "kamentsev" <notifications@github.com> a scris:

**Comment by kamentsev** [comment]
No, it does`n work with icloud account neither 

I`ve just created one  but Cydia Impactor cannot be installed with the same reason.
Development certificate costs the same 99 bucks( 

![screen shot 2017-05-17 at 19 58 24](https://cloud.githubusercontent.com/assets/28754998/26166215/7130915e-3b3b-11e7-942d-8577b8210da0.png)
![screen shot 2017-05-17 at 19 59 58](https://cloud.githubusercontent.com/assets/28754998/26166216/71461f9c-3b3b-11e7-84f7-f2b500e0771a.png)

**Comment by kamentsev** [comment]
I managed to sideload iDOS2.ipa but still files access is restricted and I cannot add anything using ifunbox or any similar apps

**Comment by DosDokTor** [comment]
Reinstall its driver mine worked well, i even used win98 in that emulator

Pe 17 mai 2017 20:37, "kamentsev" <notifications@github.com> a scris:

**Comment by kamentsev** [comment]
Which driver are you talking about?
BTW are you under IOS 10.3.2?

**Comment by DosDokTor** [comment]
No, sorry, i upgraded few days ago to 10.3.2, the driver has the name
"Bonjour" it is provided by iTunes (that's why you should update iTunes
every single time) but... I am a sad internet pirate and i don't have the
money to buy any app on the app store so i steal them from the web, i
verify them after that i go sideload them if they're good enough (i do
manage to modify them for my own usage).

Pe 18 mai 2017 18:35, "kamentsev" <notifications@github.com> a scris:

**Comment by kamentsev** [comment]
I have latest iTunes version installed.

Are you sure you can have sandbox file access under 10.3.2?

**Comment by DosDokTor** [comment]
Yes,very sure as i run iDOS 2 without ANY problem, edit the idos 2 config
and go run it without choice.com to not put you to choice

Pe 18 mai 2017 7:15 p.m., "kamentsev" <notifications@github.com> a scris:

I have latest iTunes version installed.

Are you sure you can have sandbox file access under 10.3.2?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/litchie/dospad/issues/11#issuecomment-302459160>, or mute
the thread

**Comment by kamentsev** [comment]
Yeah, I can run iDos2 without any problem as well but I cannot and add anything to it because file file access is restricted. 

How do you add any apps to iDos2? 
iFunbox or any similar app will not work under iOS 10.3.2

**Comment by DosDokTor** [comment]
They do work, i even got small linux distros to boot in it, but very
difficult. You want a program especially for DOS or you want to emulate any
operating system cuz i have an app who only can be installed using
sideload, it's name is iBox, i can send it to you, it is a port for iOS of
Bochs, it has a menu where you can configure and the OS img files you can
add them from iTunes, it never reached App Store so Apple never restricted
its access to sandbox.

Pe 19 mai 2017 9:22 a.m., "kamentsev" <notifications@github.com> a scris:

> Yeah, I can run iDos2 without any problem as well but I cannot and add
> anything to it because file file access is restricted.
>
> How do you add any apps to iDos2?
> iFunbox or any similar app will not work under iOS 10.3.2
>

**Comment by kamentsev** [comment]
Can you please share iBox app with me?

**Comment by jason0611** [comment]
Since Apple has enhanced the maximum count of test users, is it possible to re-add me as beta tester for iDOS2?

Kind regards / Viele Grüße,
Martin

**Comment by KusanagiShiro** [comment]
I too would like to be in the beta. My email is Zhane.Masaki@gmail.com.

My purchase was made before 90 days ago so I don't have the receipt anymore however, i can screencap it in my purchase history if need be

**Comment by lasergeekuk** [comment]
I use a DOS based program for raytracing laser beams. I have been using it on my iPad with iDos but I am now looking for another emulator to run it. Is there any way I can add my raytracing program to iDos2 without having to jailbreak my iPad?

**Comment by patmur66** [comment]
I too would like to be in the beta. My email is patrick at murisier.ch

My purchase was made before 15 days ago so I don't have the receipt anymore however, i can screencap it in my purchase history if need be

**Comment by lasergeekuk** [comment]
Please tell me if you get a reply, I have not had any response to my request for file sharing and I still really need a DOS emulator for iPad that works.  Neal

**Comment by jabz10** [comment]
This guy is making money off the app then never replies to anyone asking to be put on the beta.
Basically you are being ripped off.

**Comment by litchie** [comment]
If you wish to be included in beta, follow the guide here:

https://litchie.com/posts/20151027-idos-update-ios9.html#disqus_thread

I can't process email request immediately. iTunes connect is very painful to use, therefore I prefer to process requests in batch manner.

**Comment by patmur66** [comment]
Hello 

I understand that is painful to give us the access to the beta version. Could you give us a date when this are done, please. End of week, end of month. 

I send you on the mail address idos@litchie.com the confirmation of invoice for the app. My Apple-is is : patrick@murisier.ch

Thank you very much.
Patrick Murisier 

Von meinem iPhone gesendet

**Comment by lasergeekuk** [comment]
Hi Chaoji,

Thank you very much for inviting me to iDOS2 beta.
I will start testing it as soon as I have loaded my ray trace program.
Is there a link to instructions on how to add my program to the program list that you could send to me?

Thanks again

Neal

Neal Croxford
DeBe Lasers Ltd.,
Appley Court,
Appley Wood Corner,
Haynes,
Bedfordshire
MK45 3QQ, UK
neal@debe.co.uk
www.debe.co.uk
+44(0)1234 381107
+44(0)7714 750934

**Comment by litchie** [comment]
If you click on iDOS2 in iTunes file sharing section, you could see the files. Among them is play.bat, and you can add program entry into the batch file.

**Comment by RetroMal** [comment]
I've purchased iDOS2 today and updated to the latest iTunes on my PC but iDOS2 doesn't appear amongst the apps that can share files.  Am I doing something wrong ?

**Comment by remino** [comment]
I am also looking for iDOS 2 in the iTunes File Sharing section, but it is not there. Do I need to sign up for the beta for this feature?

**Comment by style95** [comment]
Hi, Kindly invite me for the beta version.

* email: style9595@gmail.com

**Comment by alansmid** [comment]
Hi Chaoji,

Thank you very much for inviting me to iDOS2 beta.
I will start testing it with an iPhone X, Any News for the compatibility? I’m looking forward to testing the landscape mode!

**Comment by lasergeekuk** [comment]
Hi Litchie,

I have just gone to use iDOS2 and it says the TestFlight beta has expired.

Can you restart the TestFlight?

Thanks in advanced


Neal


Regards
 
Neal




 Neal Croxford  |  Director  
 
T +44 (0) 1234 381107  |  M +44 (0) 7714 750934
 
neal@debe.co.uk  |  www.debe.co.uk

**Comment by f1d0** [comment]
Hi Litchie, just bought iDOS2, can you also pls add me in for beta for file sharing?

Cheers,

Filip

**Comment by balmiervegasloungeact** [comment]
Hi Litchie, 

If possible, please also add me in for the beta file sharing? Much appreciated. 

Cheers,
Paul

**Comment by pikapark201** [comment]
Please send me a beta copy that has file sharing as well!

myhacknull@gmail.com

**Comment by style95** [comment]
It seems this is not being maintained anymore.

**Comment by fuzzywolfhakaru** [comment]
Please send me a copy of the beta with file sharing! danielburbank@gmail.com Thank you!!! :)

**Comment by javasjavasjavas** [comment]
Hi , i bought the App last week. I Want to be in the beta please . I need file sharing option. My email is javdamico@gmail.com . Thanks!

**Comment by Zillah666** [comment]
I need the file sharing option for idos2, can you help me. My email is : zillah666@gmail.com.
Thx

**Comment by NNNN618** [comment]
Add me please, my email: nan.618@qq.com
Thanks!

**Comment by style95** [comment]
This thread is no more active, I also requested the invitation in last year, but got no response yet.
So please do not leave any comment here anymore, all people in this thread will be notified by new comments.

**Comment by theoccupier92** [comment]
> I'd like to invite you to a beta version (with File Sharing enabled). Need your email.

Hi my emAil is rustolya92@yandex.com

**Comment by AndreyKamski** [comment]
Also want to join beta
please give me a code to TestFlight

**Comment by AndreyKamski** [comment]
My email: 9175353@gmail.com

**Comment by GeekOnSkates** [comment]
Any news on this?  I've tried using iExplorer (a Windows app for transferring files), but iDOS doesn't show up (apparently there is some setting that has to be enabled in the app) so that's a no-go.  I've downloaded and tinkered with several file explorer apps; no dice.  I've tried everything short of jailbreaking my iPad.  This is one of those apps that makes me wonder why I ever bought the dumb thing lol... but at least they haven't locked-down Edit, so I can at least goof around with batch scripting... anyway, back on topic, is the beta still a thing?  I saw some really old posts talking about there being one, but since there's no info since November I thought I'd check in.

PS: I haven't found much in the way of documentation; I don't know Swift or Objective-C, but I'd be happy to contribute once this issue is resolved.  This has the potential to be a truly amazing app, and I am rooting for you guys.  Anything I can do to help, just let me know. :)

**Comment by DosDokTor** [comment]
Hey, man, i used every iDOS version out there, no matter where you put the
files, it could be /var/mobile for example. Once you "mount D /" i could
run dos executables from anywhere. Non jailbreak. I don't know what kind of
invisible wall you hit... It was and is always running properly on my iOS
devices...

**Comment by DosDokTor** [comment]
Eh, eh, btw, are you sure it's not your iOS? It's very easy to corrupt the
file system, you might try to restore your iPAD through iTunes.

**Comment by GeekOnSkates** [comment]
Interesting ideas; not sure where you got them (which is why I offered to help with instructions lol) but I gave "mount D /" a try and got "mount root is harmful".  Also, does iOS even have a normal file system?  Cuz /var/mobile sounds an awful lot like Linux, and I've never seen anything like that on an iPhone/iPad.  Don't get me wrong: I'm sure iOS has some kind of uber-locked-down secret file system of some sort, but the average Joe User can't do much with it AFAIK.  I could be way off in right field on that too though.

**Comment by DosDokTor** [comment]
If it doesn't allow you to mount root, mount /var/ (root shortcut in unix)
and you are somehow right. But not fully... iOS is not linux. It is UNIX,
more precisely, BSD... but the filesystem is the same as a good old mac.

**Comment by DosDokTor** [comment]
Once you have access to /var/ or /, you can mod anything on that
filesystem. It is not complex at all... it's just BSD, what's so special
about it? But when you get access to root, don't delete anything that you
don't understand, especially the mach_kernel. It is the core of the
operating system. If you remove it, you'll have to restore the iPad using
recovery mode.

**Comment by GeekOnSkates** [comment]
Yeah, this is all news to me, cuz I've never used a Mac (lol).  I was a Windows guy for like 25 years and then switched (almost completely) to Linux a couple years ago.  And my experience with iOS has been that it's all hidden behind apps; there's a "Files" app that doesn't let you navigate to different folders (except for the one it gives you, which I doubt is / or /var/).  That's why my understanding of how it all works is limited at best.

Anyway, I can mount /var/ but again, can't change to drive D.  Entering "D:" gives an error, "illegal command D:."  Also, how would I put files into /var/ or wherever?  It may be BSD under the hood, but I have yet to see an app that lets you work with it like on any other OS.  btw thanks for the quick reply on all these "dumb" questions. :)

**Comment by shalom500** [comment]
Dear Litchie
Please send me a beta version with file sharing thanks

shalomhayun8@gmail.com

**Comment by The-Alok** [comment]
Hi litchie, I just purchased iDOS2 on app store and found fileshare is not available, requesting you beta version. Thanks !

alok125554@gmail.com

**Comment by litchie** [comment]
see #84
