### ISSUE TITLE
NumPad Opaque issue

### ISSUE THREAD

**Issue by gadismetal** [litchie/dospad#121]
Hello, I am using iDos2 on iPhone X. I noticed that when I press the transparent NumPad key, it turns opaque.  I agree that transparent keys sometimes make mistakes.  However, NumPad doesn't have as many keys as a joypad, and I think it's unlikely to make mistakes even if it stays transparent.  Rather, when entering numbers with NumPad, the bigger problem is that the numbers in the lower right corner are hidden so that I cannot see any numbers.  (Please refer to the screenshot attached below) 
![39344B58-FFE4-4069-9461-5214F4BCE60C](https://user-images.githubusercontent.com/80968663/111796511-a175e300-889e-11eb-9093-84c467928ad2.jpeg)
![BC59D56E-4E2D-4943-8B9A-88E50273DAEF](https://user-images.githubusercontent.com/80968663/111796518-a33fa680-889e-11eb-9c12-80dbdb3f5697.png)

In particular, the size of the joypad key and the NumPad key does not differ significantly, but pressing the joypad key does not change to opaque.  I think it would be great to add an option to keep it transparent even if I press the NumPad key in the settings.  Thank you for reading my opinion.

**Comment by litchie** [comment]
The numpad will become opaque on any typing, but then return to transparent after idling for a few seconds. I guess in your case, you use it a lot, so it is opaque most of the time.  

We can add an additional button to numpad so it will be movable like the full keyboard. A setting to keep it always transparent will also be considered.
