### ISSUE TITLE
<CMD>+<TAB> breaks external keyboard support (Apple Smart Keyboard Folio)

### ISSUE THREAD

**Issue by swobi71** [litchie/dospad#122]
I use iDOS2 and press CMD+TAB on my Apple Smart Keyboard Folio to change to another App. 
When I return to iDOS2 the external keyboard is no longer recognized.
If I use the touchscreen to switch apps (swipe up and left) it does not happen.
Could you please look into that?
Thanks!
   swobi
BTW: In DOSPAD this is not a problem

**Comment by litchie** [comment]
Should be fixed in next app store release.

**Comment by swobi71** [comment]
THANKS! I'll give you feedback as soon as it is available.
all the best
   swobi
