### ISSUE TITLE
How to expand drive space

### ISSUE THREAD

**Issue by don17sch** [litchie/dospad#125]
I am trying to install games and I got the error with one game that I ran out of room on the drive. I have at least 1TB of space left on my iPad so I know the issue is with the app. Is there any way to increase the amount of virtual space that iDOS can see when active?

**Comment by SuperKenVery** [comment]
The space idos can use should be unlimited. You said there wasn't enough 

发自我的 iPhone

在 2021-7-13，上午9:48，Donald Schickel ***@***.***> 写道：

**Comment by SuperKenVery** [comment]
Could you provide more details? 

On which drive is it reporting not enough space? Did you mount an img as that drive?

Which game are you installing? Does this problem occur with other games? 

Anyway, a screenshot or a **complete** error message should be helpful.

**Comment by don17sch** [comment]
![80FD781B-D7AF-47C9-BD08-08ADE1196B87](https://user-images.githubusercontent.com/35238939/125380103-48532300-e357-11eb-98ee-34ce0c090aa7.png)
![88735EB9-C5E9-4DF1-B9BE-86573438D5D2](https://user-images.githubusercontent.com/35238939/125380108-48ebb980-e357-11eb-9549-0914dd23cf32.png)

**Comment by don17sch** [comment]
![4DF09950-10B0-414F-AA79-08994464C2C8](https://user-images.githubusercontent.com/35238939/125380196-6caeff80-e357-11eb-92bc-98043df71de1.png)

**Comment by don17sch** [comment]
This is how much room the dir command shows is currently free on my dos drive

**Comment by don17sch** [comment]
split this into multiple comments to format it a bit better.

**Comment by don17sch** [comment]
![812A1A39-1765-4D86-8E53-73394F26729F](https://user-images.githubusercontent.com/35238939/125380483-dd561c00-e357-11eb-84c1-9a2387a30cbe.png)

**Comment by don17sch** [comment]
One last screen shot to show you the file size needed for this install option

**Comment by SuperKenVery** [comment]
iOS doesn't restrict a single app's disk usage. It creates a folder for each app. As shown in the dir command, there's a lot of space available. 

Again, does this occur with other games? Or just this one?

**Comment by SuperKenVery** [comment]
Results from googling:
You should specify "-freesize xxx" when mounting a file system directory onto a DOS drive, where xxx is in mb. 

However this is not easy to do on idos. You can install the game on dosbox on a computer, and then copy the whole folder where you installed dagger fall to idos, and then run it.

**Comment by don17sch** [comment]
dir shows a drive space of 262MB no matter how many files I delete. So the problem is not that I do not have enough space but that I cannot install something that needs more than that amount of space.

**Comment by litchie** [comment]
> Results from googling: You should specify "-freesize xxx" when mounting a file system directory onto a DOS drive, where xxx is in mb. However this is not easy to do on idos. You can install the game on dosbox on a computer, and then copy the whole folder where you installed dagger fall to idos, and then run it.

Thanks for the tip. Will try to adjust the free size when mounting a directory on start up.

**Comment by don17sch** [comment]
> 
> Results from googling: You should specify "-freesize xxx" when mounting a file system directory onto a DOS drive, where xxx is in mb. However this is not easy to do on idos. You can install the game on dosbox on a computer, and then copy the whole folder where you installed dagger fall to idos, and then run it.

what is the command to mount a drive in iDOS? I tried mount but that says it is an illegal command

**Comment by don17sch** [comment]
I was able to solve this problem  using @litchie commit 3555efdf9fb6e809948f319825d3ab874a3c5a82
I installed the github version instead of the store version. @litchie I added a zero to your freesize command and I now have more than enough room for anything I would need to do. Probably would have been fine with the defualt but I like to go big. 
with this commit I no longer have this issue
