### ISSUE TITLE
Typing exit at prompt hangs app

### ISSUE THREAD

**Issue by nscaife** [litchie/dospad#126]
Steps to reproduce:

1. Open iDOS (no custom configuration; straight to C:\\> prompt)
2. Type `exit` and press return.

Actual result: After step 2, the app (including GUI features) freezes and needs to be force-closed.
Expected result: Simulate reboot, power off, or do nothing if this is the last interpreter to close.

Hardware: iPad Pro (12.9-inch) (5th generation) w/ Magic Keyboard
OS: iPadOS 14.6

**Comment by Moklonus** [comment]
I just found out about this app today. I've been looking and can't find an answer, does the Magic Keyboard and Trackpad work in the app, like you'd expect or is it bluetooth only?
Thanks.

**Comment by litchie** [comment]
A proper reboot is hard to implement, and since you can not self terminate in iOS, I guess the only option is to do nothing at all.
