### ISSUE TITLE
Sound not working on iPad Pro M1

### ISSUE THREAD

**Issue by sven-borkert** [litchie/dospad#127]
Hi,

it seems that sound is not working with the new 2021 model iPad Pro with M1 processor. So far I tested this with Doom2, and it's working without problems on my iPad 6th generation, but fails to produce any sound on the new iPad Pro.

Regards,
Sven

**Comment by sven-borkert** [comment]
Tested with Maniac Mansion and Command & Conquer demo. Same problem, sound working on the 6th gen iPad, but not on the iPad Pro with M1.

**Comment by litchie** [comment]
I don't have a M1 iPad Pro at this moment, so it may take a while for me to investigate. Meanwhile does this problem exist for any other game as well?

**Comment by sven-borkert** [comment]
So far I reproduced this with Doom2 shareware version, Maniac Mansion demo and Command & Conquer demo. Did not find any game that produced sound on the M iPad Pro so far. Is there any game you want me to test with? I was searching through an archive of old free dos games, but many were crap and did not even start. If you know any game/tool I should test with, send me a link and I will do.

**Comment by litchie** [comment]
@sven-borkert  Can you send an email to idos@litchie.com ? I would like to share some links with you in private.

**Comment by litchie** [comment]
No reproducible
