### ISSUE TITLE
Release IPA  on 2.1 while App Store is at 2.6.2

### ISSUE THREAD

**Issue by lonkelle** [litchie/dospad#129]
This keeps sideloaders unable to sideload anything except version 2.1. So, if this gets removed by Apple in the end - release IPAs would be a godsend. ☺️

**Comment by misterbeebee** [comment]
Now that iDOS was removed from AppStore :-(, an updated build would be especially useful to have on GitHub.

**Comment by litchie** [comment]
iDOS will be released thru Testflight & AppStore. There won't be binary releases in github
