### ISSUE TITLE
Appeal App Store Guidelines

### ISSUE THREAD

**Issue by MisutaaAsriel** [litchie/dospad#130]
As it was recently announced, due to the ability to import files into iDOS, Apple gave the ultimatum of [removing iDOS 2 from the app store, or removing file import from the app](https://9to5mac.com/2021/07/22/idos-2-emulator-for-ios-to-be-removed-from-the-app-store/) (which would make it effectively useless). As such, it was decided to take it down from the store.

However, I strongly believe that the rule itself for which iDOS 2 was removed should be contested. **Unfortunately, only the developer of an app can contest App Store rules, and only as part of the appeals process during a rejection.**

> Appeals: If you ... **would like to suggest a change to the guideline itself**, please [submit an appeal](https://developer.apple.com/contact/app-store/?topic=appeal). This may help get your app on the store, and it can help us improve the App Review process or identify a need for clarity in our policies.

In particular, according to reports, Apple responded to your app with the following:

> Specifically, your app executes iDOS package and image files and allows iTunes File Sharing and Files support for importing games. Executing code can introduce or changes features or functionality of the app and allows for downloading of content without licensing.

However, I believe that this is a **mischaracterization** of iDOS 2, its functionality, and the type of application it even is. Furthermore, I believe that the guideline itself that this is relating to is **misguided**, lacking particular nuance and distinction.

—

For starters, **the ability to load packages into iDOS 2 does not "introduce or change features or functionality" of the app.** — _Unlike a virtual machine, or an IDE which can compile and execute "native" code,_ **iDOS 2 functions more similarly to, and in the same vein as, a web browser. It is providing a sandboxed environment, with a _hardened_ set of features, in which to _interpret_ code within the framework of its featureset.**

Just as a web browser can only utilize the HTML, CSS, and other web technologies that have been built into the engine, so too can iDOS 2 only utilize the features and functionality that is built into the software. — **An example would be CD hardware simulation.** While iDOS 2 does provide MSCDEX simulation, and the ability to expose files as disks in _software_ when running under iDOS 2's simulated DOS environment, **it does _not_ provide simulated IDE CD hardware**. So when software is ran _directly_ under iDOS 2, using the _BOOT_ command, software cannot see CD drives.

In this, software, ran atop iDOS 2, **is unable to extend or change functionality of the software**. Software ran atop of iDOS 2 can only utilize the features and functionality which iDOS 2 already provides, and it is up to the software as to **which** features it utilizes, rather than _adding_ features as Apple suggests.

—

Additionally, the idea that iDOS 2 "allows for downloading of content without licensing" **is also a gross mischaracterization, or at best, a misunderstanding.** — Unlike emulators, whether it be for modern PC hardware; or for game systems, where content for older machines is still being licensed through official emulation; **iDOS 2 only provides access emulated 286/386/486 hardware, and a simulated DOS environment.** Software, made for MS-DOS, as well as DOS-based operating systems themselves, **are no longer being licensed, or made available to the general public in any official capacity.**

Whilst the _source code_ of these programs may be _intellectual property_, these applications are no longer licensed at all, and are considered abandonware. Copyright is not enforced, original copies are not guaranteed to even be in existence, and generally, there are no "official" avenues of obtaining the software further.

Furthermore, _iDOS 2 does not directly facilitate the downloading of code_. It is up to the user to provide their own files, and to where those files are obtained are not of concern of the iDOS 2 applications. _If a user previously owned a legal copy of the software in use, then they have every right to use it within iDOS 2 in some form._

—

In all, Apple's guidelines show a clear lack of nuance towards software tools, which operate with a limited framework and a sandboxed environment, much like a web browser or other similar tool, as they are treated as if they are no different from tools which operate _outside_ the sandbox, without limitation, and with APIs disallowed by Apple.

Likewise, when these tools provide no method of directly accessing content from the web, instead, relying on users to supply their own files, it in no way facilitates "downloading content". Whether users sideload the content, by loading it off an external drive, access it directly through use of a modern USB disk-drive, or whether they do in fact download the software from the web, these tools have no way to know. In order to "facilitate" downloading content, the software itself would need to provide network functionality, a way to directly access content from the web, and a way to download said content, none of which tools like iDOS 2 do.

Tools like iDOS 2 provide great educational benefit, allowing users to learn more about older software, and the history of computing, through experience; something that cannot be done whilst "making the source code completely viewable and editable by the user." — There is historical benefit to applications like iDOS, and much of the software it runs in question is already provided through Archive.org, a **non-profit internet library** which has numerous major, educational supporters, and has even received donations from **the Library of Congress**.

—

Ultimately, I don't know if you'd want to go through this trouble of appealing the guidelines themselves. I don't know how much of a hassle it'd be to make such an argument as the ones above.

But I don't think it was fair either how your app was treated. **It was only taken down after articles painting it as receiving favoritism during an anti-trust lawsuit**, after all. That isn't coincidence. — News outlets made unfair comparisons about your software, which in turn pressured apple to make a decision one way or another about the features of your app.

Speculatively, the fact that an option to remain in the store, but with core functionality removed that would render the software useless, is a sign that Apple **does** see benefit in iDOS 2 existing in the store, and the option they gave was moreso possibly encouragement to remove it from the store to "save [Apple] face".

**Comment by litchie** [comment]
@MisutaaUrufu Thanks for your help. I already appealed, but seriously, I can't write as good as this, although the points are basically the same. This is a good reference when we need more elaboration.

**Comment by cyberluke** [comment]
I personally dont need to import any package,  mapped c drive from sandboxed internal storage folder is already enough.

**Comment by cyberluke** [comment]
Okay, I agree with you. Thanks for clarification. Microsoft, Geforce Now and Google Stadia have the same problem. They went with streaming through Safari browser. There is js-dos and https://dos.zone which already works, but they do not have implemented MFI support in Safari. I'm lucky to have the original iDOS available and it works with Razer Kishi MFI.

**Comment by MisutaaAsriel** [comment]
> Okay, I agree with you. Thanks for clarification. Microsoft, Geforce Now and Google Stadia have the same problem. They went with streaming through Safari browser.

A bit off topic but the reasoning, AFAIK, is different between those and iDOS. — iDOS is running "executable code" that "changes the behavior" or introduces additional functionality to the app. This is **technically** in violation of 2.5.2:
> Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code which introduces or changes features or functionality of the app

Meanwhile, the issue with GeForce Now, Stadia, and Xcloud is that the apps functionally cannot adhere to iOS' app rating system in a way both parties see fit. — iOS has parental controls which allow age restricting apps and games, but Xcloud/Stadia/GFN are all singular apps, which would have a singular rating. Apple has positioned that these apps could allow circumventing Apple's ratings guidelines, as if a parent allowed access to one of these apps, with in-app purchases, children would have full access to any content on their storefronts, without restriction.

There's also the issue of iAP and support; Microsoft, Google, & Nvidia have been hard pressed that they would like users to be able to purchase games from their storefronts in-client. Apple posits this as circumventing the app store, whilst opening Apple up to customer support issues. — I don't necessarily agree with this one, but they've been pretty public on this. **Steam Link is on the App Store, for example, because it only allows users to access an existing library**.

My argument in my original feedback, btw, was that **iDOS meets an exception laid out in 2.5.2**, and that, furthermore, 2.5.2 _should be expanded upon_:
> Educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code provided that such code is not used for other purposes. Such apps must make the source code provided by the app completely viewable and editable by the user.

iDOS source is openly available here on GitHub, and in no way was piracy or abuse encouraged. Only after popularity and potential misuse by various media outlets was it removed.

2.5.2 is also somewhat narrow, as there are some apps which provide a _historically_ educational benefit by executing code. Being able to run old software in an educational environment can be used to allow students to understand the history of computing in a more interactive manner than a textbook, whilst being more accessible and versatile than reviving an old machine. It's hands-on learning.

**Comment by litchie** [comment]
Closing: https://litchie.com/2024/08/idos3-approved
