### ISSUE TITLE
Move to Altstore

### ISSUE THREAD

**Issue by SARankDirector-Minecraft** [litchie/dospad#133]
If the attempt to appeal the App store guidelines fails, You should move over to Riley Testut’s Altstore so that you can continue iDos.

**Comment by AMODLT** [comment]
Gracias

**Comment by DanTheMan827** [comment]
AltStore doesn't do paid apps though...

**Comment by litchie** [comment]
Closing: https://litchie.com/2024/08/idos3-approved

**Comment by kostasal26** [comment]
altstore is very good at my opinion.
