### ISSUE TITLE
imgmount for mixed mode cd's and compressed audio tracks

### ISSUE THREAD

**Issue by vga-256** [litchie/dospad#134]
I noticed that the internal imgmount does not appear to support BIN/CUE sheets that used compressed audio (e.g. MP3/OGG) for audio tracks. The image fails to mount via imgmount.

Behaviour:
Could not load image file: /ipad folder...../Krondor/KRONDOR.cue
MSCDEX: Failure: Invalid file or unable to open.

I re-tried using raw redbook audio tracks, and the cue sheet loaded properly.

[This article suggests that Dosbox must be compiled with SDL_Sound](https://www.linuxquestions.org/questions/slackware-14/cannot-mount-cue-images-in-dosbox-0-74-a-4175421232/) in order to enable compressed audio track support.

**Comment by litchie** [comment]
Is it possible to share the files for testing?

**Comment by Benno79** [comment]
Hello, I have the same problem. Ogg files are not playing. Same error as above. I cannot load a cue file.

**Comment by litchie** [comment]
Would you be able to provide some test files? idos@litchie.com

**Comment by Benno79** [comment]
Sure. With pleasure. I'll send you everything later. I would be really happy if I could play the game with music. It works smoothly under Boxer, Dosbox etc. Only iDos doesn't want it.Am 12.09.2024 03:48 schrieb Chaoji Li ***@***.***>:
Would you be able to provide some test files? ***@***.***

**Comment by Benno79** [comment]
Hi, here is the link to the game.
It would be great if you could get it to work. It works perfectly but unfortunately the audio files are not played. Don't be surprised, the GOG.ins is the same as a cue file. I've already converted it to Cue and IMG or Bin. Unfortunately it doesn't work either.
Thank you very much and especially for the great APP!!! Kind regards, Benjamin
https://drive.google.com/drive/folders/1-FV3GmUhD-zc_v9yypQLX7hEyodNI7Hv?usp=share_link￼

**Comment by Benno79** [comment]
Any news for the Problem? 
Thx

**Comment by litchie** [comment]
Try testflight build: https://testflight.apple.com/join/86LrYm5n

**Comment by BennoRetro** [comment]
Hi, Sound works perfect. Only Issue is direct Touch. It doesn't work now. If it works correctly, for me it's perfect.  many many THX for your work.

**Comment by litchie** [comment]
Compressed sound tracks is supported in latest appstore release (v3.2) @BennoRetro  direct touch should also be fixed now.

**Comment by Benno79** [comment]
Thank you so much 👍🏻👍🏻👍🏻👍🏻Von meinem iPad gesendetAm 22.10.2024 um 06:19 schrieb litchie ***@***.***>:﻿
Compressed sound tracks is supported in latest appstore release (v3.2) @BennoRetro  direct touch should also be fixed now.
