### ISSUE TITLE
Enable MIDI playback via CoreAudio

### ISSUE THREAD

**Issue by DominusExult** [litchie/dospad#138]
@litchie when we were working on Exult you told me that CoreAudio is not working on iOS. It's been a few years since then but I enabled it in Exult via https://github.com/exult/exult/commit/0972bd912422f43356085fd9ee593f6dbf0a2913 and AFAIR DOSBox uses similar code to Exult. So it might work after all and not that hard after all :)
And yes, you need a soundfont, whatever iOS uses by default is pretty bad...

**Comment by litchie** [comment]
I remember that I could not get it compiled because some APIs were missing, guess I didn't dig enough:). 
Anyway, wonderful news!
