### ISSUE TITLE
New App Store Guidelines

### ISSUE THREAD

**Issue by DanTheMan827** [litchie/dospad#145]
The App Store guidelines have been updated and now specifically allow emulators.  Just fyi

**Comment by litchie** [comment]
The guidelines isn't very clear, but definitely worth a try

**Comment by nanonomad** [comment]
Have you tried to reapply? There are a number of really terrible emulators for Gameboy that managed to make it through.

An alternate strategy could be to possibly package it along with DJGPP as an MS-DOS programming learning tool and see if they allow that. If you manage to get back on the store let me know and I'll post a video about it on my YouTube channel to get the word out.

**Comment by litchie** [comment]
Yes, I tried. Still waiting though. ( https://litchie.com/2024/04/new-hope )

**Comment by drcursor** [comment]
Have you thought about distributing via an altstore - https://rileytestut.com/blog/2024/04/17/introducing-altstore-pal/ ?

**Comment by MisutaaAsriel** [comment]
Riley's own Delta [was approved for the App Store](<https://apps.apple.com/us/app/delta-game-emulator/id1048524688>), so there's hope!

**Comment by leszek-s** [comment]
UTM SE virtual machine was recently accepted on the app store and apparently people even launched windows xp on it. So maybe now there is a chance for iDOS in the app store?

**Comment by litchie** [comment]
Closing: https://litchie.com/2024/08/idos3-approved
