### ISSUE TITLE
How do I mount a different folder as c drive on startup?

### ISSUE THREAD

**Issue by Banjo-Oz** [litchie/dospad#151]
I added this to the DOSPAD.CFG file but it doesn't seem to work.

[autoexec]
MOUNT -u c
MOUNT c .\drivec
C:

Typing the first two commands manually *after* boot does work, so it's not the commands. It just seems like the [autoexec] section is being run before the default mounting rather than after it (as would be expected). How do I fix this?

PS I also tried

[autoexec]
MOUNT -u c
MOUNT c ~/Documents/drivec
C:

but that has the same result (works on commandline, ignored in config file).

**Comment by litchie** [comment]
iDOS automounts ~/Documents folder as C. I think we probably can detect the drivec folder which can be detected and used as root for C.

**Comment by litchie** [comment]
Use `*.idos` package format and tap on it from Files app to launch iDOS, then the package will be mounted as C.

**Comment by litchie** [comment]
Or name the drivec folder as `C.harddisk`
