### ISSUE TITLE
[Feature Request] Fluidsynth and soundfont support

### ISSUE THREAD

**Issue by Banjo-Oz** [litchie/dospad#154]
Being able to add a *.sf2 soundfont file to the config folder (and inside *.idos packages) would be fantastic, and give a LOT more options for midi music.

As it stands, is there any way to get "general midi" music on iDOS? I notice setting DOOM to "general midi" gives no music. Is this expected behavior?

I am so used to using a SC-55 soundfont on my PC that DOOM in iDOS sounds so "wrong" now using just soundblaster music (though I have got Gravis Ultrasound music working nicely).

**Comment by thevolumeremote** [comment]
> Have you tried mt32: https://litchie.com/2020/11/idos-update-v2.4

I can confirm MT32 is working - tested with Space Quest 3. (in config make sure mididevice=mt32 and MT32_PCM.ROM and MT32_CONTROL.ROM are present)

**Comment by litchie** [comment]
Also probably related:  #138

**Comment by litchie** [comment]
As of now, sound font is supported.
