### ISSUE TITLE
Games using mouse are unplayable on iPad with bluetooth mouse because of system circle cursor.

### ISSUE THREAD

**Issue by jorycz** [litchie/dospad#159]
Games using mouse are unplayable on iPad with bluetooth mouse because of system circle cursor, which shows notification center when reach top of the screen and dock when reach bottom of the screen. Both actions pause game and bottom edge sometimes close iDOS 3 and return to home. Mouse cursors (game arrow and system circle) are out of sync.
Please see screenshot. iPad Pro 11" 2018. Latest iPadOS 17.6.1

UTM SE hides & sync cursors somehow, can something [here in source](https://github.com/utmapp/UTM/blob/main/Platform/iOS/Display/VMDisplayMetalViewController%2BTouch.m) help?

![image](https://github.com/user-attachments/assets/7d0e92a8-e119-4091-b437-9b38d5e15981)

**Comment by eduo** [comment]
In particular, seems to be here:
https://github.com/utmapp/UTM/blob/main/Platform/iOS/Display/VMDisplayMetalViewController%2BPointer.m

and 

https://github.com/utmapp/UTM/blob/main/Platform/iOS/Display/VMCursor.m

**Comment by jorycz** [comment]
Thank you for sample sources correction.

**Comment by eduo** [comment]
Are you sure you're using iDOS 3? I've been testing a lot and I don't see the circle cursor at all. 

I will test with Dune 2 which you have in your screenshot, since it may be specific to some mouse implementations.

**Comment by jorycz** [comment]
Yes, current App Store version. It's not only in Dune 2 it's everywhere. Norton Commander and other games. That circle is iPadOS cursor. Are you testing on iPad with bluetooth mouse?

**Comment by eduo** [comment]
> Yes, iDOS 3 current App Store version. It's not only in Dune 2 it's everywhere. Norton Commander and other games. That circle is iPadOS cursor. Are you testing on iPad with bluetooth mouse?

I tested with a trackpad and the pointer didn't show.

Then I hooked up a bluetooth mouse while the game was running, and the pointer appeared.

Then I killed the application and started the game again and the pointer no longer appeared. 

Now I can't make the pointer appear no matter how I start the game and whether the mouse is connected or not when I start it up. I don't get a pointer when in DOS either. It seems to be properly masked. iPAD OS effects from the jmouse are also not visible (for example trying to pull the home bar, the three dots at the top or trying to move the mouse pointer to my mac). The native mouse is completely blocked from iDOS 3 except if I add a new one while the app is running.

Are you using the latest version from the app store?

**Comment by jorycz** [comment]
I am using latest release bought from App Store allowed by Apple recently. I made video with this issue https://youtu.be/wsIuQXuAEsE
You can see on video, that I tried some things that sometimes help.
For example, if I wait a bit (someone called me) and then returned to game, system cursor was gone and since then, all was OK for the rest of the run. Another time, when I switched to another app and returned to game, system cursor was also gone. But 95% of the time, it behaves like you can see on attached video. This time no switch or waiting (until system cursor fades) helped.

**Comment by eduo** [comment]
I have been testing this thoroughly and on an iPad Pro 11" with the latest iOS beta I can't see the circle pointer.

I loaded Discworld and the circle pointer appears a few seconds  before iDOS takes over. The game cursor is visible the rest of the game. If I switch back and forth the circle is visible a couple of seconds and then goes away

**Comment by jorycz** [comment]
> If I switch back and forth the circle is visible a couple of seconds and then goes away

This not happen to me unfortunately. Circle cursor reappears again when I move mouse as you can see in the video I posted in previous post.

Basically the video says it all.

Thank you for your time spent with testing.

**Comment by eduo** [comment]
I know this will sound like a stupid question, but in the video you don't ever click the mouse that I can see. You move it and then kill the app. 

Unless I'm mistaken the mouse is captured after the first click and only then the circle disappears. Are you clicking at all and the circle persists? You mentioned you had used many games and NC, so I assumed you'd been clicking to test (when you click make sure to use the program's pointer and not the iPAD circle to target something).

**Comment by jorycz** [comment]
Question is ok but watch the whole video. I click the mouse several times. Mission was started by clicking for example.

**Comment by mstrshikadance** [comment]
I am having this same problem. Use to work perfectly, but since yesterday i get both cursors. In game cursor and also the IPad dot. I am using latest App Store version with iPad Pro and iPad Magic Keyboard/trackpad. iOS 18.1. 

was playing under a killing moon for days without the issue..not i get both.

**Comment by jorycz** [comment]
I udpated one iPad to iPadOS 18 yesterday and issue still persist.

**Comment by litchie** [comment]
I am unable to reproduce this problem with iPadOS 17.6.1 and a Bluetooth mouse. But sounds like this is a problem that quite a few people are seeing.

**Comment by jorycz** [comment]
Today I connect USB-C mouse and issue is the same. So it's not related to bluetooth only.
Also I noticed that iDOS 3 (updated to latest version) ignored mouse when connected first time. I need to (force) kill app and open again.

**Comment by litchie** [comment]
Upgraded iPad (9th gen) to iOS 18.0, still can't reproduce the problem.

**Comment by eduo** [comment]
Same here. I'm on ipad OS beta 18.1 beta 4 and still don't see it. It may be something very specific of some models? Specific of some peripherals?

**Comment by jorycz** [comment]
Guys do you have hardware keyboard? Issue seems to be related to HW keyboard. As soon as I don't have keyboard connected, mouse is working as expected. 

As soon as I connect Smart Folio keyboard or even USB-C keyboard, system cursor appears and mouse issue is back. 

When I disconnect keyboard and reopen iDOS 3 or restart iPad without HW keyboard, mouse is OK again.

**Comment by jorycz** [comment]
I think I found what exactly trigger this issue.

It is "Modifier Keys" mapping setting of the HW keyboard in iOS. You can find it in **Settings > General > Keyboard > Hardware Keyboard > Modifier Keys**. Here, you can map Escape key to some HW keys.

Here, If you set **Caps Lock Key** (or other key) action to **Escape** key, system cursor appear instantly and trigger this issue.
As soon as you use **Restore Default** in **Modifier Keys** menu even with attached keyboard, mouse is behaving like expected (Turn off display/lock iPad and reconnect BT mouse to return to normal mouse behaviour).

Why I did it. After I installed iDOS app and tried some games, I found out that iPad Keyboard mapping is not working for Smart Folio Keyboard in app settings. For DOS games, ESC key is really basic key. So I map Esc to Caps Lock key in iOS HW keyboard settings.

Now I see 2 ways how to help people with Apple Smart Folio Keyboard. Fix system cursor (when something nasty happens) in case Escape is mapped to any HW keyboard key in iOS settings, or add mapping for this keyboard to iDOS settings so it's not necessary to remap it in iOS.

There are more layout versions so there is different "key picture" in upper left corner. Don't know if the scan code is the same or not though.

- US
![](https://eshop.macsales.com/images/_gallery_/bin/APLMU8H2LLAB-pimid85743-xl.jpg)
- CZ

![](https://d25-a.sdn.cz/d_25/c_img_H_GP/EVkR1o.jpeg)

**Comment by jorycz** [comment]
Another thing I observed, maybe it helps with testing. When you hit **CMD + .** (period) system cursor appear and mouse stop working. This shortcut (cmd with period) is system Escape key emulation in iOS.

**Comment by litchie** [comment]
Hi Josef, that's very good findings. Thanks for digging into it. I will follow up on that clue.

**Comment by litchie** [comment]
I was able to reproduced the problem, and we should have a fix soon.

**Comment by litchie** [comment]
I have been trying the same hack UTM used, but it seems not very stable in iDOS. The system cursor still pops up now and then, especially when clicking. And the system dock sometimes would also pop out and mess things up. UTM doesn't seem to have this issue though. Still working on it, but will take more time than I expected.

**Comment by jorycz** [comment]
Fingers crossed! I can install ipa through Altstore in case some testing is needed. 
Can’t wait to finish my X-COM and Red Alert missions :)

**Comment by jorycz** [comment]
Unfortunately almost same behavior. First I got this one https://youtu.be/BQds7j7uQe8
Then I reset modifier keys in Settings (so I lost ability to use Escape) and test it again. Mouse works well.
Then I tried to use alt/option key as Escape key in mapping and got slightly different behavior https://youtu.be/zeF7hIHqs3Y but I could not be related.
I noticed there is sometimes minor difference in cursor behavior if you run app when system cursor is showing and when not.

**Comment by litchie** [comment]
How about we make COMMAND+\ (Backslash) inside iDOS to mean escape?

**Comment by jorycz** [comment]
Would it be doable to add button to the top panel under settings gear icon, that would wait for any pressed key and map it to Escape key and store it (so you don't have to do that every time)? This would be universal solution and everyone with any layout can map any suitable key to Escape.

If not, your solution will work also of course.

My point is just to make it a little bit more universal with ability to setup Escape key to left top corner for any layout.

**Comment by litchie** [comment]
@eduo How about COMMAND+, (COMMA) then?  I would like to keep it simple if possible. In future, these would be configurable with per-game settings.

**Comment by eduo** [comment]
That's also pretty convenient (it's the shortcut for settings in mac applications but probably not an issue in iDOS)

**Comment by litchie** [comment]
@jorycz in the latest appstore version you should be able to use `COMMAND+,` for escape. That's what we can do for now.

**Comment by jorycz** [comment]
@litchie escape key mapping to CMD+, is working OK.

But sometimes (very often) it stays in loop. Check this https://youtu.be/kvQUnqUFkTs
It’s the same behavior I described in my other issue #160 - sometimes it stays in loop and it seems like you are pressing the key again and again.

Should I open this issue or you want to track it in #160?

**Comment by litchie** [comment]
We can track it in #160.

**Comment by Rhystic1** [comment]
I know this issue has been closed, but I am still having this issue. No matter what game I'm playing on iDOS, if I have a mouse plugged in to my iPad I keep seeing the system mouse pointer, which, as you can imagine, is very annoying and makes games like Quake pretty much unplayable. I have tried every possible option in the iPad settings with no success. 

This behaviour does not occur on other emulators such as UTM. @litchie

**Comment by iyerusad** [comment]
iPad Pro M4 13 w/ Magic Keyboard 
iOS 26.2
iDos 3 v3.3

Seeing similar/same issue with [HOMM1](https://www.gog.com/en/game/heroes_of_might_and_magic) and [HOMM2](https://www.gog.com/en/game/heroes_of_might_and_magic_2_gold_edition) -- the in-game cursor and system cursor shows on initial launch and they are out of alignment.

Pressing `CMD`+`,` pops out of iDos and going back to iDos -- the system cursor is gone and game cursor is working/aligned! If there is a config setting that could added that would autolaunch into this mode for some games, could be nice addition.

However noticing following substantial quirks:
- In-game Movement is interrupted because double clicked mouse is cancelled:
  - When moving in HOMM game, double clicking moves along the path to destination. However once tried the `CMD`+`,` trick, any double click to travel goes one step and requires double clicking again and again to get to destination.
- When exited HOMM2, the command line shows tons of `\` characters typed
  - Can confirm happens only after tried the `CMD`+`,` trick -- if I don't do that, the command prompt exits to the expected `C:\HOMM2>`
- In HOMM1 unable to launch the save/options menu -- it pops up and disappears (suspect because a key press is happening in the background)

That aside, new user to iDos and dosbox in general -- pretty cool to see classics on iPad via your app.

**Comment by iyerusad** [comment]
**Potentially resolved issue/new discovery:** Launching the iDOS package file **_using a Shortcut_** (that opens the file) launches into game with fully working mouse/single in-game cursor!! 

Confirmed when opening manually via Files app results in the dual mouse cursors (in-game and iOS cursor).

**Comment by TwitchyMcJoe** [comment]
Found a work around. If you launch in full screen, and then window the iPad app, you can get the cursor to work at the sacrifice of the app being in a window. I was able to replicate it multiple times with Daggerfall. It might take a couple of cycles windowing and fullscreening the app, but it worked.
