### ISSUE TITLE
Direct touch broken in recent update

### ISSUE THREAD

**Issue by Bow-ser** [litchie/dospad#165]
Direct touch, where you can tap on screen and the mouse clicks where you tap, no longer works with recent update. Please fix! It is an *awesome* feature I'm sad to lose, and of course stupid Apple won't let me downgrade the app to version 3.0.
iDos 3.1, iPhone 12

**Comment by litchie** [comment]
Thanks for reporting this issue. There was a piece of code lost when merging with latest dosbox source. Will fix in next update.

**Comment by litchie** [comment]
Should be fixed in latest AppStore version (4a00e1c5)
