### ISSUE TITLE
Move Mouse Buttons

### ISSUE THREAD

**Issue by convolutionbbs** [litchie/dospad#19]
Hello,
I'm using an external keyboard and not having tab, function keys, etc. work was troublesome for some old Sierra titles (I know this is an Apple issue).

I figured out how to create a new configuration for dosbox and was able to setup a small button shortcut keyboard by modifying the ui.cfg file to only show a few small buttons and no dpad.  

Is there a way to add a mouse right click / left click binding to buttons in the ui.cfg?

If not - is there any way to move the mouse buttons from the right to the left side of the screen when showing mouse mode?  I'm a righty and would like to use my left hand for the clicks.

I think someone else mentioned having mouse and joystick / keyboard simultaneously - that would be helpful too.

Thanks!

**Comment by litchie** [comment]
In latest version (v2.3), mouse buttons in landscape mode are movable. Please reopen if it doesn't work as you expected.
