### ISSUE TITLE
ios9 compatibility broke

### ISSUE THREAD

**Issue by convolutionbbs** [litchie/dospad#22]
I upgraded an iPhone 6+ to ios9.  When I try to launch iDOS 2 it gets as far as showing the app briefly but then crashes.  This worked fine prior to the upgrade in ios 8.4.1.

Hope to see this get fixed - thanks.

**Comment by litchie** [comment]
#7c5bf93 fixed crash on launch, and #0afe0d7 fixed opening settings crash.

Still we got two crashes to fix:

  -  iPhone rotating
  -  Showing modal view controller

**Comment by convolutionbbs** [comment]
Great thanks!

Will at least this fix make it to an update app release?  Does anyone know if this works on an iPad Air 2 in ios9?

**Comment by DennisNg** [comment]
Not sure about iPad Air2 but my iPad mini 3 under iOS9 work fine.  Even alt-F key to use my assembler editor is ok. In fact given the following alt-f issues with iPhone kind of device, I download the app in case it does not work again.  

iP5c apps under iOS 9 can go in ok, but the alt key e.g. alt-F to call up the menu is not.  You press alt it does not register as on and hence you cannot do alt-f.  Try many times.  

iP4(!) ios7 (not ios9) is still not working but the behaviour is a bit different, the alt-f combination becomes a sort of tab key.  Still cannot use the alt-f to do my compilation.

iPhone6+ under ios9 did have that issue.

**Comment by patrickbusch** [comment]
Rotating does crash on my iPhone 6s on 9.1

**Comment by convolutionbbs** [comment]
I just updated to iDOS 2 v 1.4 and it worked fine with my iPad 4th gen (128gb) at 8.4.1.  I took the plunge and updated to iOS 9.1.  iDOS does not crash, but my Bluetooth keyboard support is no longer functioning.  Any thoughts?

**Comment by convolutionbbs** [comment]
Trying to (unsuccessfully) troubleshoot this here.  iPad 4th gen 128gb (9.1) Bluetooth keyboard is not functioning, but I can get Bluetooth keyboard working ok on iPhone 6+ (9.1).  I have a custom configuration folder setup on the iPad and wondering if that has something to do with it.  The new iDos 2 v1.4 sees the custom configuration from pre-update on the iPad.  Even if I use default keyboard is not functioning.

However, I can't get iDos2 to show up in file sharing within ITunes 12.3.1 on Win 8.1 x64 either with iPhone or iPad.  This means I cannot copy or retrieve any files to and from the application on either iPhone or iPad.  This makes it difficult to do anything with the app or troubleshoot.

Is anyone else having the file sharing issue?

**Comment by litchie** [comment]
should be fixed now
