### ISSUE TITLE
MiFi Gamepad Support

### ISSUE THREAD

**Issue by SasanOne** [litchie/dospad#23]
Hey can you support MifI Gamepads with configurable controls? That would be a dream as you could play System Shock etc like a boss ;)

**Comment by yoshisuga** [comment]
I'm working on a custom version of iDOS that's based on an older version of iDOS, and added experimental mfi controller support:
https://github.com/yoshisuga/iDOS/tree/mfi_controller

If you can compile and run it, it'll work..but probably only for iPhone (what i'm testing it on)

I can't get this current repo to work because I can't figure out how to fix the crashing issue.

**Comment by SasanOne** [comment]
hey,

can you please make an .ipa version of it? Then I can test it :)

Thanks,

Sasan

Von meinem iPhone gesendet

**Comment by yoshisuga** [comment]
Here's a link to the .ipa:
https://mega.nz/#!SZZkHbjR!r1elE6dZ5iX1yG9oJuQhyuU3qzWVRln-jJDeqYW3oFQ

To remap controls, go into landscape mode and you should see an "R" button. Tapping it goes into key remapping mode, and bringing up the keyboard and tapping on a key will let you bind the key to a controller button. Tapping the "R" button again switches off remapping mode. It's rough, but functional right now.

**Comment by SasanOne** [comment]
Hey,

you are a genius :) it works flawlessly. I tested with Lost Vikings, Commander Keen 4 and 5 and even System Shock.

Wow. Now I can play action/sports games with idos and not only strategy and adventures. The touch controls never worked great in fast action intense games.

Wow!!!!

Thanks so much,
Sasan

Von meinem iPhone gesendet

**Comment by litchie** [comment]
@yoshisuga Hi,  could you please share more information about the crash? It would be great if we can have your change here.

**Comment by SasanOne** [comment]
The Remap button is missing on my iPad Pro. My ethusiastic review was based on the use on iPhone 6s. Can you make it work on ipads? Thanks :-)

Von meinem iPad gesendet

**Comment by SasanOne** [comment]
On iPads it loads the iPad version of idos. Perhaps you can make a non-Universal app as a quick fix so that I can play on iPad :-)

Von meinem iPad gesendet

**Comment by yoshisuga** [comment]
@litchie Yes, see my comment on this issue:
https://github.com/litchie/dospad/issues/34

Changing the orientation causes an EXC_BAD_ACCESS error. I enabled only landscape orientation but would run into this crash again, after trying to show a UIAlertView.

I tried to diagnose the issue using NSZombie tracking and Instruments but couldn't find where something was getting released prematurely.  I'm guessing it might be something to do with SDL but I'm not too familiar with it so I can't really figure out what's going on.

I'd love to bring in these changes, and I went down the road of adding them, but this crash is preventing me from adding this change.

**Comment by yoshisuga** [comment]
@SasanOne Glad you liked the change! I myself was motivated to play some games :) 

I know iPad support isn't there yet - I hacked it to work with iPhone because that's what i was testing on.

Adding iPad support shouldn't be too hard - i first wanted it to just work, and now I can go back and move some of the logic to the shared base controller class.

**Comment by SasanOne** [comment]
Can I donate some money to you for your excellent work?

I am looking forward for the iPad support :)

Can you also make an idos version with win98 preinstalled and a large virtual drive (3 gig and more)? I always fail to achieve that :( I only get win 3.11. working :) but with win98 we coul play many many more games :)

Von meinem iPhone gesendet

**Comment by litchie** [comment]
@yoshisuga That's interesting. So your fork doesn't have this crash problem? It would be interesting to see the difference between current version and your earlier fork, although the SDL part should not have changed.

**Comment by SasanOne** [comment]
his version does not crash on the iPhone 6 and 6s when you turn it from portrait to landscape

Von meinem iPhone gesendet

**Comment by yoshisuga** [comment]
@SasanOne Running win98 on dosbox through iDOS/dospad? Wow that is quite ambitious :) Unfortunately that's something I don't think I can help with. It looks like there are guides out there on how to get DOSBox running with Win9x, and I think you can do most of it with DOSBox itself by typing commands into it. 

I appreciate the offer for a donation, but no need for that :) I did this out of my own satisfaction/enjoyment, and i'm glad someone else found it useful!

**Comment by yoshisuga** [comment]
@litchie Yeah my fork doesn't have the crashing issue. If it's not SDL,I'm not sure what could be the cause :(

**Comment by litchie** [comment]
Thanks, I'll look into it and merge your changes myself.

**Comment by SasanOne** [comment]
ok thanks :)

any ETA for the iPad version? :)

Von meinem iPhone gesendet

**Comment by yoshisuga** [comment]
@litchie I can volunteer and transplant my changes to this repo - i'll create a fork and then do a pull request with the changes.

@SasanOne ETA is very soon - I just moved most of the logic to be shared among both iPhone and iPad, and the iPhone one still works. Got the button to appear on the iPad and it seems to work ok too. Just need to test it on an actual iPad with the controller pairing. The landscape keyboard appears to be a little messed up but you should still be able to make out the keys to map.

**Comment by SasanOne** [comment]
You can send me the ipa and I can test on iPad Air 2 and iPad Pro (the large model) :)

Von meinem iPhone gesendet

**Comment by yoshisuga** [comment]
Here's the IPA that supports iPad (i think):
https://mega.nz/#!aIJ1wK5A!QKMICGjokiEayraYTGq6EbbZ2gA9W1xNr_j1hbYLZgc

It didn't work with my iPad 2 I had on hand but I think it might be because the MadCatz controller i had isn't compatible with it.

I ran it on the simulator for iPad Pro and the landscape keyboard appears a little messed up. Functional still, I think.

I'm gonna make a pull request for these changes on this repo so it can go back to where it belongs.

**Comment by SasanOne** [comment]
it works :) fantastic. Remapping is a bit hard with the little messed up keyboard but a bit trial and error gets it done :)

Kudos!!! You rock! Works on all of my iPads with all games ;)

Sasan

Von meinem iPhone gesendet

**Comment by litchie** [comment]
@yoshisuga Thanks.  There are a lot of differences. Your version of dospad turns on ARC, which we don't have yet, and also we have changed the UI since, so it may take a good weekend's work.  I'll merge the main differences, and please help to make sure MIFI still works after I update. I don't have a MIFI device here.

**Comment by litchie** [comment]
@yoshisuga I have created a separate branch fix2016. Currently it has your change in, however, I have no idea whether it actually works. Please help to fix it, and port your ipad changes in. 

I have temporarily disabled 64bit build for the moment, so you should be able to test it in landscape mode. #34

**Comment by yoshisuga** [comment]
@litchie Working on it now :) There are a few things here and there i need to patch up but so far its looking good! Thanks for doing that!

**Comment by yoshisuga** [comment]
@litchie Here's my pull request:
https://github.com/litchie/dospad/pull/36

Made some fixes to make it work properly and made the UI just a little bit more presentable.

I used the dospad target for testing; the iDOS target wasn't working for me but I think it just had to do with the PLAY.BAT file in there not correctly responding to keys? I didn't want to mess with that so i just used the dospad target instead and it worked fine.

**Comment by litchie** [comment]
@yoshisuga I just did a merge. Please check the master branch.  The iDOS is working. I guess the reason it's not responding is that there is nothing in diskc/apps/*. If you look into PLAY.BAT, you will know why.  If the selected entry doesn't exist, then it will just return back to the menu, giving you an impression that it's not responding.

**Comment by SasanOne** [comment]
you can just edit the play.bat and delete all entries and save it and then it will work like normal old idos :)

Von meinem iPhone gesendet

**Comment by yoshisuga** [comment]
Ah, I just was lazy and didn't touch the play.bat file :)

Here's the IPA:
https://mega.nz/#!TUZ1AZaY!KpGNVc4gJKulDsKh8qUMA-8cet43d64l2p0sXF9SgkU

Now that mfi support has been properly added to the main repo, all is well! 👍

**Comment by SasanOne** [comment]
Thank you :)

Von meinem iPhone gesendet

**Comment by SasanOne** [comment]
@litchie: can you release the latest build of yoshisuga on TestFlight? That would be great!

Von meinem iPhone gesendet

**Comment by SasanOne** [comment]
Hey,

is there a working idos with mifi enabled with iTunes file sharing? Can someone send me the .ipa or .deb file?

Thanks in advance :-)

Regards,

Sasan

Von meinem iPhone gesendet

**Comment by SasanOne** [comment]
Is there a 64Bit mifi enabled dospad version?

Thanks :-)

Von meinem iPad gesendet

**Comment by bitzaros** [comment]
Hello everyone!
could someone please share an IPA for dospad that runs on ios 11 and has MFI controller support?
The links above are no longer working.
Thank you all in advance!!!

**Comment by SasanOne** [comment]
I second that question :-)

Von meinem iPhone gesendet

**Comment by yoshisuga** [comment]
Here's a link to an IPA I just built because my certificate expired:
https://mega.nz/#!nEhChIqa!wNTKTahvkp5OMlxyLAF_lOjn0bv7M5b0zxUzKecv1TE

I made some minor changes, like locking the orientation to landscape on iPhone to prevent a crash, and supporting opening the files using the Files app. I'll try to make a PR later for this.

**Comment by bitzaros** [comment]
Wow! Thank you so much @yoshisuga !!!! I will try it on my iPad Pro!

**Comment by SasanOne** [comment]
Really great!

Von meinem iPhone gesendet

**Comment by maciekish** [comment]
Hi, is this currently working? I have a Steelseries Stratus connected to my iPad Pro and confirmed working with an MFI test app from the App Store. When i try it in iDOS nothing happens even when using the dpad in a game menu that can be navigated using arrow keys. I'm using the github version of iDOS, not App Store. However there are two targets in the project, maybe im supposed to run dospad and not iDOS?

**Comment by litchie** [comment]
MFi gamepad support is now reimplemented in v2.1 to support better key mapping and multi-player.

**Comment by SasanOne** [comment]
great, do you have an .ipa that I can resign? :-)

Von meinem iPhone gesendet

**Comment by litchie** [comment]
See the releases page.

**Comment by SasanOne** [comment]
ok thanks :)

Von meinem iPhone gesendet
