### ISSUE TITLE
Settings won't work in cydia DOSPad 1.4 and other things

### ISSUE THREAD

**Issue by shadelegend333** [litchie/dospad#32]
Button takes me to the settings app for iOS,  that doesn't have anything for dos pad, instead of showing any settings for it.

The config file is blank instead of showing any settings to configure.

Also, I suggest instead of spreading the files through the mobile\Documents folder to have a dedicated folder for everything dospad in documents.

**Comment by litchie** [comment]
cydia build is not maintained any more.
