### ISSUE TITLE
8way dpad

### ISSUE THREAD

**Issue by Agnakaraara** [litchie/dospad#33]
Hello,
I love your app and I have some features that could be really nice if added:
1) 8way Dpad (diagonals like in aemula)
2) lanscape mode for iphone (i have 4S and i cant put in into landscape :( )

Thank you very much for your efford

**Comment by litchie** [comment]
8 axis dpad should have been supported in v2.2. Please check.

**Comment by Agnakaraara** [comment]
Haha that's funny, I wrote this comment in 2016 and I also wrote that App Store review in 2020 and I wondered how did you get my mail xD Nevertheless, iDOS is now the best app on my iPhone. Thank you so much for the blazingly fast response!!! (Well it took 4 years, but also 1 week, depends :D ) I wish you good luck man!

**Comment by litchie** [comment]
Yeah, I saw your review on appstore. If a feature is requested twice, it must be worth doing it :-) Since I was rewriting the gamepad for iPhone, I thought maybe we should do it. I hope there won't be angry people asking for 4 way option back. I hate adding settings.
