### ISSUE TITLE
iPhone 6- Landscape Mode crashes 

### ISSUE THREAD

**Issue by Shugabuga** [litchie/dospad#34]
Landscape mode seems to be unsupported on the iPhone 6; it crashes the app. It sometimes works, though (got it to work, and then failed later).

**Comment by Shugabuga** [comment]
``

**Comment by yoshisuga** [comment]
Happens on main.m line 323:
`int retVal = UIApplicationMain(argc, argv, @"DosPadUIApplication", nil);`

Trying to debug it but not sure why its crashing here. 

This is the backtrace:

```
* thread #1: tid = 0x6fde8f, 0x000000010d507817 libobjc.A.dylib`objc_msgSend + 23, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x200000003)
    frame #0: 0x000000010d507817 libobjc.A.dylib`objc_msgSend + 23
    frame #1: 0x000000010ac5a4ac UIKit`__39-[UIWindow _noteOverlayInsetsDidChange]_block_invoke_2 + 213
    frame #2: 0x000000010b52921a UIKit`__51-[FBSScene(UIApp) updateUIClientSettingsWithBlock:]_block_invoke + 245
    frame #3: 0x000000010f249d78 FrontBoardServices`__46-[FBSSceneImpl updateClientSettingsWithBlock:]_block_invoke + 11
    frame #4: 0x000000010f249de9 FrontBoardServices`-[FBSSceneImpl updateClientSettingsWithTransitionBlock:] + 67
    frame #5: 0x000000010f249d67 FrontBoardServices`-[FBSSceneImpl updateClientSettingsWithBlock:] + 86
    frame #6: 0x000000010b5290e8 UIKit`-[FBSScene(UIApp) updateUIClientSettingsWithBlock:] + 139
    frame #7: 0x000000010ac5a3b0 UIKit`__39-[UIWindow _noteOverlayInsetsDidChange]_block_invoke + 155
    frame #8: 0x000000010abf3f62 UIKit`_runAfterCACommitDeferredBlocks + 317
    frame #9: 0x000000010ac07e4c UIKit`_cleanUpAfterCAFlushAndRunDeferredBlocks + 95
    frame #10: 0x000000010ac14147 UIKit`_afterCACommitHandler + 90
    frame #11: 0x000000010d99bc37 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    frame #12: 0x000000010d99bba7 CoreFoundation`__CFRunLoopDoObservers + 391
    frame #13: 0x000000010d9917fb CoreFoundation`__CFRunLoopRun + 1147
    frame #14: 0x000000010d9910f8 CoreFoundation`CFRunLoopRunSpecific + 488
    frame #15: 0x000000010fcb0ad2 GraphicsServices`GSEventRunModal + 161
    frame #16: 0x000000010abe7f09 UIKit`UIApplicationMain + 171
  * frame #17: 0x00000001072f307d dospad`main(argc=1, argv=0x00007fff58914670) + 1261 at main.m:324
    frame #18: 0x000000010ec2392d libdyld.dylib`start + 1
```

**Comment by litchie** [comment]
The crash only happens in 64bit build.

**Comment by yamashir0** [comment]
iPhone 6, iOS 10.3.3, Xcode 8.3.3, 32bit build: no issues. 64bit build with 2.5s delay works but crashes on orientation change.

Updated to Xcode 9.2 for iOS 11 support: 64bit build still crashes on orientation change.

Updated to iOS 11.4.1: 64bit build now magically crash free :)

**Comment by litchie** [comment]
I don't have an iPhone X device, but orientation change on the simulator still crashes.

**Comment by yamashir0** [comment]
iPhone simulator crash free for me. I can’t recall if simulator crashed when I was using Xcode 8.3.3, but no problems now under 9.2.

All my previous comments above are for iPhone 6 device. I was avoiding iOS 11 update for the longest time because I didn’t want to lose iDOS2 ;)

**Comment by hanaldo** [comment]
An interesting finding: on my iphonex, the app needs to be started while holding the phone in Landscape mode, it will always crash if holding the phone in Portrait mode. After the app fully started, then the orientation change will no longer crash the app. Not sure if this helps anything...

**Comment by litchie** [comment]
Thank you for sharing. This kind of bugs are the most annoying.

**Comment by litchie** [comment]
Should be fixed for good in latest version. 
The evidence has been lying in the stack trace but I am just too dumb to notice.
