### ISSUE TITLE
DiskC is empty or not found

### ISSUE THREAD

**Issue by iTommy258** [litchie/dospad#39]
I downloaded your xCode Project, because i want to use this App on my iPad Mini 2 (9.3.2). I purchased the app but thats not the point, because i want to use windows 95. If i am at the root of "C" and type "dir" it tells me, that the drive "C" is not found. Could you fix this or tell me how could i fix this?

**Comment by JasjarJasjar** [comment]
Type Z:

**Comment by iTommy258** [comment]
Won't work on the iOS Xcode injected version. I am trying to run Windows 95. 

Von meinem iPhone gesendet

**Comment by JasjarJasjar** [comment]
How to get windows 95:
1. Download windows 95 from here: http://www.mediafire.com/?85w636eic9sv12h
2. Download iexplorer from here: https://www.macroplant.com/downloads
3. Plug in your device and run iexplorer
4. Copy the extracted file "W95.img" to the folder titled Documents
5. Type in DosPad "imgmount a D:\W95.img"
6. Type in "boot D:\W95.img"
7. It might not boot the first time so try again and it will work

**Comment by iTommy258** [comment]
Thx I want to try it later 

Von meinem iPad gesendet

**Comment by iTommy258** [comment]
Sorry for disturbing again. I can’t find Documents on iexplorer.

**Comment by JasjarJasjar** [comment]
What folders do you see?

**Comment by litchie** [comment]
Please reopen if this issue still exists.
