### ISSUE TITLE
Smart keyboard support

### ISSUE THREAD

**Issue by EriolGaurhoth** [litchie/dospad#40]
Hey all, it would be really awesome to add smart keyboard support to dospad.  As it stands, the letter keys, number keys, and any other "single press" key works fine, but any multi-key commands (i.e. using "shift" to capitalize a letter) or toggle commands (i.e. caps lock) are not supported for the smart keyboard.  I'm not sure how difficult a change this would be to the code, but it's something to think about.  Thanks!

**Comment by bernarddavis** [comment]
I'm not getting any key presses registered at all using a smart keyboard. Is there a setting that needs activating for this to work at all?

**Comment by landswipe** [comment]
I know what's wrong with this, I just got a smart keyboard and will supply a fix shortly.

**Comment by bernarddavis** [comment]
Great to hear, I'm looking forward to using it.

**Comment by landswipe** [comment]
EriolGaurhoth, what IOS version were you running?

**Comment by landswipe** [comment]
@EriolGaurhoth please retest and apply #43 (if it isn't merged into master), let me know if it works for you now.

**Comment by EriolGaurhoth** [comment]
I have verified this morning that the Smart Keyboard works flawlessly (including all modifiers) on my 9.7" iPad pro.  Thank you for the help!

**Comment by landswipe** [comment]
No problems :)
