### ISSUE TITLE
ld: library not found for -lcrt1.3.1.o

### ISSUE THREAD

**Issue by lolman8776** [litchie/dospad#47]
Total XCode noob.
Using xcode 8.0, and it can't find crt1.3.1.0.
Sorry for such a vague description. It worked fine before I updated XCode.

**Comment by yoshisuga** [comment]
Xcode 8 is missing that library file :( if you still have Xcode 7 around, it's there so you can create a symlink to it:

```
# go to your Xcode iOS SDK lib directory
cd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib

# create the symlink to Xcode 7
ln -s /Applications/Xcode7.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/crt1.3.1.o crt1.3.1.o
```

Also attached it here - maybe you can copy it to your lib directory:
[crt1.3.1.o.zip](https://github.com/litchie/dospad/files/526048/crt1.3.1.o.zip)

**Comment by lolman8776** [comment]
Thank you! Copying that file worked.
