### ISSUE TITLE
File sharing needs to happen

### ISSUE THREAD

**Issue by 1Heroblack1** [litchie/dospad#48]

**Comment by JasjarJasjar** [comment]
It is impossible to turn file sharing on, apple will reject any update that attempts to turn file sharing back on. Dospad is a newer version of iDos which fixes all those problems. Click the clone or download button to download Dospad. You will need xcode to install it though.

**Comment by ChristopherDrum** [comment]
@Jasjar42 And where and how do you install software into this? I have Dospad built and running on my iPhone using iOS 11. I can see my Documents folder in iTunes. I've added a "games" folder and in Dospad I get nothing. I cannot `cd games` ("Unable to change to: games"), and `dir` at C:\ prompt gives me `File *.* not found`
