### ISSUE TITLE
Bluetooth Keyboard issues on Cydia DosPAD

### ISSUE THREAD

**Issue by KubbaYioka** [litchie/dospad#51]
Hello,

I'm still fairly new to the JB scene, so bear with me here. 

I've read in other places (and here on Github) that in order to get an external bluetooth keyboard to work with DosPAD, you need a developer build or the Cydia version.

I downloaded the Cydia version, but can't get the app to work with my keyboard. Is there something else I missed? 

Thanks.

**Comment by lolman8776** [comment]
This version works for me, non jailbroken. Just compile it.
