### ISSUE TITLE
Provisioning Profile Expired

### ISSUE THREAD

**Issue by CyberManifest** [litchie/dospad#53]
How can I compile and run this now on my iPhone now that the provisioning profile expired?

```
The operation couldn’t be completed. Unable to log in with account 'ryan.k.mckee@gmail.com'. An unexpected failure occurred while logging in (Underlying error code -1004).
Provisioning profile "iOS Team Provisioning Profile: HLDK844H7.unique.litchie.dospad" expired on Feb 5, 2017.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'
```

**Comment by vincentneo** [comment]
You need your own Apple developer account to compile. It's free over at apple's developer website.
I remember that you can't use the same bundle identifier as well, change it a little bit and it should work.

**Comment by CyberManifest** [comment]
I looked into this, and it turns out that it's unavoidable due to Apple policy, provisioning profiles are set to expire 30 days.
