### ISSUE TITLE
iDOS 2 Beta expired

### ISSUE THREAD

**Issue by csomigliana** [litchie/dospad#57]
Hi,
I'm (was) using iDOS 2 Beta on a iPad 3 with some  custom old dos apps (compiled with turbopascal 5.0) and it was going fine. Yesterday I started getting the message "iDOS 2" Beta is expired when I launch it form the desktop and it is now tagged as "Unavailable" in TestFlight.
Is this correct (i.e Beta period really expired)?
Any chance to activate it again?
Many thanks in advance for any support.
Best regards,

**Comment by litchie** [comment]
We will keep beta running as long as possible.
