### ISSUE TITLE
iDOS 2 File Sharing

### ISSUE THREAD

**Issue by DomTrues** [litchie/dospad#58]
I've been wanting to put programs on my iDOS 2, but no file sharing. I tried alternative methods, but no avail. Is there a download available for a licensed iDOS 2 that has file sharing?

**Comment by SuperKenVery** [comment]
Download filza escaped on next.tweakboxapp.com

**Comment by IsThatLogic** [comment]
To put the files you want to to the path /var/mobile/containers/data/application/idos2/documents/app if you didn’t already know.

**Comment by SuperKenVery** [comment]
![a21191f2b2119313d76d51006c380cd791238d23](https://user-images.githubusercontent.com/39673849/44636865-82fa2480-a9e0-11e8-877f-1fdd62084048.jpg)
