### ISSUE TITLE
File sharing disabled again in iDos 2 in appstore

### ISSUE THREAD

**Issue by hu10xiaorui** [litchie/dospad#67]
In the App Store, I brought iDos to emulate dos to play dosgames and emulate 98 etc. After I download iDos 2 I found out that I can’t import my games and windows 98 into iDos because file sharing is disabled. I am thinking of is it possible to install iDos 1 or enable file sharing

> I tried Cydia impactor but the service is down.

> I can’t sync ipa files by iTunes because my Mac is brocken and I can’t find the apps tab on windows to install my app.

**Comment by hu10xiaorui** [comment]
I also would like to know how to change the cpu cycles

**Comment by IsThatLogic** [comment]
You can also download Filza excaped and put the files you want in manually.
