### ISSUE TITLE
Making dospad "touch friendly"

### ISSUE THREAD

**Issue by sectroyer** [litchie/dospad#69]
I was wondering whether it wouldn't be possible to make dospad more touch friendly. For now to move mouse we have to use small scrolling area in the bottom right corner of the screen. Wouldn't it be possible to either:
1) Make cursor appear (and click if that's necessary) where we click on screen. It could also work like that if we tap on "empty space" it moves cursor to such position but if we tap on cursor itself it left clicks once
2) (if previous not possible) make "mouse area" size adjustable or at least extend to full screen 😄 
Anyway great projects and hope it will become even better 👍

**Comment by litchie** [comment]
Should be fixed by 69762ab8f0f5ec2a1b8cd4f62d75d15c327b0ba7
