### ISSUE TITLE
Feature: Better mouse support

### ISSUE THREAD

**Issue by robbo007** [litchie/dospad#7]
Could you improve the mouse support. Maybe take in to account the way SCUMM does it? Seems hard clicking etc with right mouse clicks.

**Comment by dborca** [comment]
Hi,

I would also love direct touch, maybe as an option.  The idea is that many old games do not actually use tracking, so it can be scraped.

Also, right-click as an option (double-tap, long tap, whatever).  Many games do not use drag/double/long tap as input events so they can be reused for right-click.

FWIW, I just tried Heroes of Might and Magic II; yes, it's playable, but after half and hour my hand hurts.

I know the code is somewhere in SDL/src/video/uikit/SDL_uikitview.m and I'd do it myself, but I'm not familiar with SDL and it seems to have some internal logic attached. :)

Thanks!

**Comment by litchie** [comment]
Yes, we should have the option to use double tap as right click, and actually it's not hard to do.

**Comment by dborca** [comment]
Thanks! And what about direct touch?

**Comment by robbo007** [comment]
Direct touch is a must :D


Rob Craig
Website: www.robcraig.com <http://www.robcraig.com/>
Twitter: @robcraig

**Comment by Dainara82** [comment]
Hi, yes direct touch we really need, i hope you get it to work, for scumm vm it takes that: [url]https://github.com/scummvm/scummvm/blob/master/dists/android/README.Android[/url]

**Comment by robbo007** [comment]
Hi Litchie,

Any updates on DOSpad for iOS? I’m now running it on a 9.7” ipad pro. Could be a good time to start testing the MIDI support like in BOXER for the Roland MT32. Also direct touch for the mouse? 

Let me know. I’m happy to help test.

Regards,
Rob

Rob Craig
Website: www.robcraig.com <http://www.robcraig.com/>
Twitter: @robcraig

**Comment by litchie** [comment]
Direct touch is now supported by 69762ab8f0f5ec2a1b8cd4f62d75d15c327b0ba7
