### ISSUE TITLE
Idea/question

### ISSUE THREAD

**Issue by chrislightsaber** [litchie/dospad#70]
So I’m not exactly sure what the configuration directory is but there’s an option to change it. Could I change it to a folder in the files app so I can play games I download to the files app?

**Comment by chrislightsaber** [comment]
Or mount the files app as the directory/disk

**Comment by dylan** [comment]
This would be huge, or with the advent of external drive support, being able to use a drive directly would let me finally load things direct from media!

**Comment by litchie** [comment]
Implemented in recent updates.
