### ISSUE TITLE
Wrong drive letter on iPhone

### ISSUE THREAD

**Issue by brunocastello** [litchie/dospad#71]
I have successfully compiled your app for iPad and iPhone.

IPad Pro first gen, iPhone X. Both on iOS 12.

On iPad all OK, even the bt keyboard works. GREAT!

But on iPhone, I have only one issue: the drive letter is wrong. When I add the files through iTunes, iPad correctly saves them to C:\ but iPhone saves to D:\. Why? My Windows 3.11 is set to work from C:\, this causes a little problem for me.

Meanwhile, I also have anothe question: how hard it could be to add the ne2000 patch for dosbox to this app? I know that dosbox is included there so I am supposing that it could work.

**Comment by brunocastello** [comment]
I'm still getting that problem on iPhone X.

DOSPad thinks documents are on /var/mobile/Documents and mounts it as an empty C:\ drive, instead of /var/mobile/Containers/Data/Application/*app ID*/Documents, which is mounted as a D:\ drive. Therefore it does not reads the custom config file.

**Comment by litchie** [comment]
Now we won't try to mount /var/mobile/Documents. Should be fixed.
