### ISSUE TITLE
iDOS 2 crashing in portrait mode…

### ISSUE THREAD

**Issue by WeedyWeedSmoker** [litchie/dospad#83]
Hi @litchie!

iDOS 2 crashes when starting with portrait mode on iPhone 11 Pro Max 13.3, iPhoneX 12.4 and 6s, do you know what's happening?

Portrait mode crashes when starting with landscape mode and then turning to portrait mode on iPhone 11 Pro Max and iPhone X…

Starting with portrait mode crashes on all tested devices…

Also, there are some screen size problems on portrait and landscape modes with iPhone 11 Pro Max and iPhone X… On iPhone 6s, only in portrait mode…

Thanks!

**Comment by litchie** [comment]
Are you on the beta list? The latest build supposedly fixed this crash.

**Comment by WeedyWeedSmoker** [comment]
@litchie I just compiled the latest version, tested it on an iPhone 11 Pro Max, and it's now working perfectly!

Thanks a lot…
