### ISSUE TITLE
Join beta

### ISSUE THREAD

**Issue by shalom500** [litchie/dospad#84]
Dear Litchie
Please send me a beta version with file sharing 
Thanks

shalomhayun8@gmail.com

**Comment by litchie** [comment]
please send a request to idos@litchie.com with a receipt of your purchase.

**Comment by znah** [comment]
Hi @litchie ,
thank you for your efforts! Can you please add me to the beta testers list?
zzznah@gmail.com

**Comment by litchie** [comment]
AppStore version now has the full features. No longer need to join beta.
