### ISSUE TITLE
Dospad not Taking Touch Input on iPhone SE 2nd Gen

### ISSUE THREAD

**Issue by fat-beaver** [litchie/dospad#86]
iOS version is 13.5.1 and dospad version is the latest from testflight (1.4.1, 20200529). To add some detail: whether using the mouse tool (selected from the top bar) or not, dospad does not seem to pick up any touch input. Tested in two games and using the built-in edit utility to be sure, and all three work just fine on a first-generation SE with the same configs and game files but not on the new one.

**Comment by litchie** [comment]
Thank you for reporting.
