### ISSUE TITLE
App Store Version

### ISSUE THREAD

**Issue by DanTheMan827** [litchie/dospad#90]
The app store version doesn't allow document storage and I know that's because of the guidelines saying you can't run outside code, but Apple recently opened up the ability to appeal rejections and even challenge the guideline itself.

There are multiple apps already on the app store where their sole purpose is to run user-provided code.

- https://apps.apple.com/us/app/play-js-javascript-ide/id1423330822
- https://apps.apple.com/us/app/pythonista-3/id1085978097
- https://apps.apple.com/us/app/python-3/id1262850648

> Additionally, **two changes are coming to the app review process and will be implemented this summer. First, developers will not only be able to appeal decisions about whether an app violates a given guideline of the App Store Review Guidelines, but will also have a mechanism to challenge the guideline itself**. Second, for apps that are already on the App Store, bug fixes will no longer be delayed over guideline violations except for those related to legal issues. Developers will instead be able to address the issue in their next submission.

**Comment by litchie** [comment]
Thanks for the info. Will try our luck.

**Comment by litchie** [comment]
@DanTheMan827 Apple just approved the update. So Thank you!

**Comment by DanTheMan827** [comment]
Glad to hear!

**Comment by DanTheMan827** [comment]
Did App Store approval run into any issues or did they approve it right away?

Is it possible they didn't notice this version had file sharing, or did they reject it and you had to appeal?

I noticed you didn't include the feature in the update notes, so that's why I'm wondering.

**Comment by litchie** [comment]
@DanTheMan827 I put it in the review notes, along with some arguments why they should approve it. The review process took about 16 days, which is unusual these days. My guess is they approve it consciously. But can't rule out the possibility that some reviewer didn't pay attention to my review notes.

**Comment by daedalia** [comment]
This is awesome news. Good effort guys

**Comment by DanTheMan827** [comment]
@litchie I guess the app being featured on [How-To Geek](https://www.howtogeek.com/739100/how-to-install-windows-31-on-an-ipad/) and [9TO5Mac](https://9to5mac.com/2021/07/12/how-idos-app-lets-you-install-windows-3-1-on-your-ipad/) will really be a test of if Apple did in fact approve file sharing or if it just slipped through.

🤞

**Comment by litchie** [comment]
> @litchie I guess the app being featured on [How-To Geek](https://www.howtogeek.com/739100/how-to-install-windows-31-on-an-ipad/) and [9TO5Mac](https://9to5mac.com/2021/07/12/how-idos-app-lets-you-install-windows-3-1-on-your-ipad/) will really be a test of if Apple did in fact approve file sharing or if it just slipped through.
> 
> 🤞

Thank you for the update. I think it's about time Apple being more open about their policy towards emulators.

**Comment by DanTheMan827** [comment]
@litchie given that Apple allows educational apps to execute user provided code I say you should add in an assembly editor, maybe a code compiler

Make it into an educational app if that’s what Apple wants…
