### ISSUE TITLE
Can't compile dospad in Xcode 12.0.1

### ISSUE THREAD

**Issue by Purduecoz** [litchie/dospad#92]
Receiving the following error when compiling:

Undefined symbols for architecture arm64:
  "saa1099_device::control_w(int, int, unsigned char)", referenced from:
      write_cms(unsigned long, unsigned long, unsigned long) in libdosbox.a(gameblaster.o)
  "saa1099_device::data_w(int, int, unsigned char)", referenced from:
      write_cms(unsigned long, unsigned long, unsigned long) in libdosbox.a(gameblaster.o)
  "ncr8496_device::ncr8496_device(machine_config const&, char const*, device_t*, unsigned int)", referenced from:
      ___cxx_global_var_init.1 in libdosbox.a(tandy_sound.o)
  "saa1099_device::saa1099_device(machine_config const&, char const*, device_t*, unsigned int)", referenced from:
      CMS::CMS(Section*) in libdosbox.a(gameblaster.o)
  "sn76496_device::sn76496_device(machine_config const&, char const*, device_t*, unsigned int)", referenced from:
      ___cxx_global_var_init in libdosbox.a(tandy_sound.o)
  "sn76496_base_device::write(unsigned char)", referenced from:
      SN76496Write(unsigned long, unsigned long, unsigned long) in libdosbox.a(tandy_sound.o)
  "sn76496_base_device::convert_samplerate(int)", referenced from:
      TANDYSOUND::TANDYSOUND(Section*) in libdosbox.a(tandy_sound.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by litchie** [comment]
Got it, some files are missing. Will fix it soon, my working copy is a mess right now.

**Comment by Purduecoz** [comment]
Sounds good. Thanks for the updates!

________________________________

**Comment by Purduecoz** [comment]
There isn't a current IPA file available that I could just sign and install, is there?

**Comment by litchie** [comment]
https://github.com/litchie/dospad/releases

**Comment by litchie** [comment]
@Purduecoz Updated. Please try to compile again.

**Comment by Purduecoz** [comment]
The compile works.  Previously, I used to be able to target building a DOSPad Beta app.  Now I am targeting iDOS and do not see a DOSPad target in the Xcode project.  The iDOS compile runs OK, but I lose the first line of the DOS prompt off the top of the screen immediately (iPad Pro 11", 2nd Generation, landscape mode), and entering DOS commands beyond the beyond the bottom does not cause the screen to scroll down so that text cannot be seen either.  I can open another ticket if necessary, but wasn't sure I was building the proper target for the iPad.

**Comment by litchie** [comment]
@Purduecoz dospad target is removed during recent refactoring, because it is not much different from the iDOS target now. Previously we can't enable iTunes file sharing for iDOS.
