### ISSUE TITLE
BT Keyboard broken on iPad 9.3.5 Dospad 2.0

### ISSUE THREAD

**Issue by shockdesign** [litchie/dospad#95]
Looks like the Bluetooth keyboard support broke on the latest builds? 
I've tried building Dospad as well to debug however it doesn't seem to compile with Xcode 11... is there anything I'm missing in trying to build the app, i.e. which version of Xcode, etc.

Bluetooth keyboard works elsewhere on the iPad (i.e. Appstore, etc).

**Comment by litchie** [comment]
Make sure your build scheme is Debug or Release.

**Comment by jackazz86** [comment]
Hello, I’m having the same issue with the newly released version 2.0: my Bluetooth keyboard is not working. I’m on iPad 6 and iOS 14.0.1

It used to work on previous 1.41a.

**Comment by litchie** [comment]
@shockdesign @jackazz86 If you are using the IPA release, it's because I build with wrong configuration. Will update later. Currently working on external gamepad.

**Comment by shockdesign** [comment]
@litchie yup.. that's correct, running against the 2.0 IPA release. Awesome, will wait for the next release!

**Comment by jackazz86** [comment]
Thank you!

**Comment by litchie** [comment]
Fixed in v2.1
