### ISSUE TITLE
How to configure a bluetooth mouse?

### ISSUE THREAD

**Issue by fprimex** [litchie/dospad#98]
I see in the features listed on the app store that there is support for bluetooth mice. I am on the latest iOS and have paired a mouse. Clicks work, but the cursor does not move with the mouse movements. I can see the iOS transparent circle cursor. Is there some way to get the mouse movement events sent to the DOS environment.

Thanks!

**Comment by litchie** [comment]
It should work when you move the circle cursor into DOS screen. If cursor can not move, how do you click?

**Comment by fprimex** [comment]
Clicks with the hardware mouse buttons work, but movement moves the circle, not the game cursor.

For example, if I start Warcraft the cursor starts off on the first menu item. When I move the mouse I see the circle cursor move around but the Warcraft cursor stays still. When I click, the first me item is selected.

**Comment by litchie** [comment]
Did you move the circle cursor into the screen area?

**Comment by fprimex** [comment]
https://share.icloud.com/photos/0bSI4ZRebS0FsFPGgexXm4pDw

iOS on 14.1, iPhone XS Max

**Comment by litchie** [comment]
I see. Thank you very much for recording. It's very helpful.

**Comment by firecrafts** [comment]
im having same problem with ipad pro

**Comment by firecrafts** [comment]
this so annoying bug :(
hope you will be able to find a fix <3

**Comment by fprimex** [comment]
Just for posterity, I upgraded to 14.2 and the latest DOSPad and the issue persists.

**Comment by fprimex** [comment]
This appears to be fixed for me with the 2.6 release. Thank you!

**Comment by litchie** [comment]
Glad that it works.
