### ISSUE TITLE
Case sensitive dospad.cfg

### ISSUE THREAD

**Issue by xanthiacoder** [litchie/dospad#99]
Not sure if this is a definite thing, but it appears that when I use an editor in DOS to make changes to dospad.cfg, it saves it as DOSPAD.CFG and dosbox doesn't pick up the changes (since the lower-case dospad.cfg still exists).

And it seems to be difficult to use the Files App to change the filename to lowercase (Files App doesn't seem to allow changes to extensions so .CFG cannot be touched)

Maybe make dosbox look for uppercase DOSPAD.CFG so the file can also be edited in DOS?

**Comment by litchie** [comment]
Sure, good suggestion.
